// ===========================================================================
//
// NAVO Enterprise 2008
//
// Core interfaces
//
//
//	NEVER DEFINE LPCTSTR nor LPTSTR cause MIDL error!!!
//
//	use LPCSTR xor LPCOLESTR !!! !!!!
//
//
// ===========================================================================

import "unknwn.idl";
import "oaidl.idl";

cpp_quote("DEFINE_GUID(CLSID_VBSCRIPT,		0xb54f3741, 0x5b07, 0x11cf, 0xa4, 0xb0, 0x0, 0xaa, 0x0, 0x4a, 0x55, 0xe8);")
cpp_quote("DEFINE_GUID(CLSID_JSCRIPT,		0xF414C260, 0x6AC0, 0x11CF, 0xB6, 0xD1, 0x0, 0xAA, 0x0, 0xBB, 0xBB, 0x58);")


/* 188cb14d-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(IID_INavoErrorInfo,0x188cb14d,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb14e-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(IID_INotificationManager,0x188cb14e,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb14f-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(IID_INotificationSink,0x188cb14f,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

///////////////////////////////////////////////////////////////////////

/* 188cb150-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVO2001NotificationManager,0x188cb150,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb152-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(IID_ILockManager,0x188cb152,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb153-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVO2001LockManager,0x188cb153,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb154-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(IID_IBackupRestore,0x188cb154,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb155-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(IID_IStreamProvider,0x188cb155,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb156-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(IID_IAppDBManager,0x188cb156,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb157-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVO2001AppDBManager,0x188cb157,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb158-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(IID_IBackupRestoreManager,0x188cb158,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb159-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVO2001BackupRestoreManager,0x188cb159,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb15a-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVO2001UpStreamObj,0x188cb15a,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb15b-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(IID_ICachedData,0x188cb15b,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb15c-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVO2001_CacheServer,0x188cb15c,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb15d-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVO2001SystemObject,0x188cb15d,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb15e-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(IID_IObjectServer,0x188cb15e,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb15f-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(IID_INAVOObjectCollection,0x188cb15f,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb160-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVO2001_ObjectServer,0x188cb160,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb161-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(IID_INavoObjManager,0x188cb161,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb162-2012-4499-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(IID_IServerClientFactory,0x188cb162,0x2012,0x4499,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb162-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(IID_IServerClient,0x188cb162,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb163-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(IID_IUserDocumentDisp,0x188cb163,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb164-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(IID_IPageContextDisp,0x188cb164,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb165-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(IID_IPreprocessor,0x188cb165,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb166-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVO2001Preprocessor,0x188cb166,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb167-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVO2001Client,0x188cb167,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb168-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(IID_ISupplyInfo,0x188cb168,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb169-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(IID_ISimpleEnumId,0x188cb169,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb16a-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVO2001StreamFilter,0x188cb16a,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb16b-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(IID_IStreamFilter,0x188cb16b,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb16c-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(IID_IPingClient,0x188cb16c,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb16d-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(IID_IPingServer,0x188cb16d,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb16e-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVO2001StreamObject,0x188cb16e,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb16f-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVO2001Server,0x188cb16f,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb170-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVO2001HyperSetObject,0x188cb170,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb171-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVO2001ExpImpExportPackage,0x188cb171,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb172-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVO2001ExpImpImportPackage,0x188cb172,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb173-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVO2001InetMail,0x188cb173,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb174-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVO2001InetTransfer,0x188cb174,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb175-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVO2001InstallSession,0x188cb175,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb176-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVO2001StreamSplitter,0x188cb176,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb177-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(IID_IStreamSplitter,0x188cb177,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb178-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVO2001SocketStream,0x188cb178,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb179-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVO2002MonikerObject,0x188cb179,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb17A-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVO2002InternetProtocolObject,0x188cb17A,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb17B-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVOGM_N5GMSVR,0x188cb17B,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb17C-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVO2002SmartTagAction,0x188cb17C,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb17d-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(IID_ICntResourceManager,0x188cb17d,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb17e-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVO2002PerifComObject,0x188cb17e,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb17f-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVO2002POP3Client,0x188cb17f,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb180-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVO2002CrossInfoMan,0x188cb180,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb181-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(IID_ICrossInfoManager,0x188cb181,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb182-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(IID_IScriptCompiler,0x188cb182,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb183-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVO2002VBSCompiler,0x188cb183,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb184-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(IID_IVirtualMachine,0x188cb184,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb185-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVO2002VirtualMachine,0x188cb185,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb186-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVO2002ShellMenu,0x188cb186,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb187-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVO2002ShellNameSpace,0x188cb187,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb188-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(IID_IPreprocessedDataCache,0x188cb188,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb189-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVO2002PreprocessedDataCache,0x188cb189,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb18a-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVO2002TaskSchedManObject,0x188cb18a,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb18b-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVOGM_GM,0x188cb18b,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb18c-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(IID_IObjectServerExtension,0x188cb18c,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb18d-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(IID_IObjectServerExtensionHost,0x188cb18d,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb18e-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVOGM_SVR,0x188cb18e,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb18f-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVO2003PrintingObject,0x188cb18f,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb190-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(CLSID_NAVO2003ASPator,0x188cb190,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb191-82a4-5000-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(IID_INEDataObject,0x188cb191,0x82a4,0x5000,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb192-82a4-5000-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(IID_INEDataObjectList,0x188cb192,0x82a4,0x5000,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb193-82a4-5000-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(IID_INEDataTransaction,0x188cb193,0x82a4,0x5000,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")



/* 188cb1b1-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(IID_INUIElement,0x188cb1b1,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb1b2-82a4-4498-87d0-ebd8d9a00fb8 */
cpp_quote("DEFINE_GUID(IID_INUIContainer,0x188cb1b2,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb1b3-82a4-4498-87d0-ebd8d9a00fb8 */
//cpp_quote("DEFINE_GUID(**free**,0x188cb1b3,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb1b4-82a4-4498-87d0-ebd8d9a00fb8 */
//cpp_quote("DEFINE_GUID(**free**,0x188cb1b4,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

/* 188cb201-82a4-4498-87d0-ebd8d9a00fb8 */
//cpp_quote("DEFINE_GUID(**free**,0x188cb201,0x82a4,0x4498,0x87, 0xd0, 0xeb, 0xd8, 0xd9, 0xa0, 0x0f, 0xb8);")

///////////////////////////////////////////////////////////////////////
// INavoErrorInfo - error information storage
///////////////////////////////////////////////////////////////////////
const long UNIOPTIONS_COMPRESS_TRAFFIC_TO_CLIENT = 0x00000001;


[
	object,
	pointer_default (unique),
	uuid(188cb14d-82a4-4498-87d0-ebd8d9a00fb8)
]
interface INavoErrorInfo : IUnknown
{
	[helpstring("retrieves error information")]
	HRESULT RetrieveError
	(
		[out] long *pDataLength,
		[out, size_is(, *pDataLength)] byte ** lpBinaryData
	);
	[helpstring("retrieves error information")]
	HRESULT RetrieveError2
	(
		[out] LPSTR * ppcErrors
	);
};

///////////////////////////////////////////////////////////////////////
// INotificationManager - notification manager
///////////////////////////////////////////////////////////////////////

typedef enum tag_notifysinkclass
{
	nsc_document,
}
notifysinkclass;

typedef enum tag_objaction
{
	obj_insert,
	obj_update,
	obj_delete
} objaction;

typedef struct
{
	char		m_bCompressed;
	char		m_cExt[4];
} navostreaminfo;

[
	object,
	pointer_default (unique),
	uuid(188cb14e-82a4-4498-87d0-ebd8d9a00fb8)
]
interface INotificationManager : IUnknown
{
	[helpstring("register sink")]
	HRESULT Advise
	(
		[in] IUnknown * pONSinkUnknown,
		[in] LPCSTR pcUserName,
		[in] LPCSTR pcComputerName,
		[in] notifysinkclass eNSC,
		[out] long *pCookie
	);
	[helpstring("unregister sink")]
	HRESULT UnAdvise
	(
		[in] long nCookie
	);
	[helpstring("returns rich client info (user,computer,cookie,props)")]
	HRESULT QuerySinks
	(
		[out] long *pDataLength,
		[out, size_is(, *pDataLength)] byte ** lpBinaryData
	);

	[helpstring("notifies shared variable change")]
	HRESULT NotifySharedVariableChange
	(
		[in] long nOriginatorCookie,
		[in] long lVarNr,
		[in] VARIANT nNewValue
	);
	[helpstring("notifies specified user")]
	HRESULT NotifyUser
	(
		[in] long nOriginatorCookie,
		[in] long nDestinatorCookie,
		[in] long lEvenCode,
		[in] VARIANT * pDataVariant
	);
	[helpstring("notifies users")]
	HRESULT NotifyMultipleUsers
	(
		[in] long nOriginatorCookie,
		long nCount,
		[in, size_is(nCount)] const long * pDestinatorCookies,
		[in] long lEvenCode,
		[in] VARIANT * pDataVariant
	);
	[helpstring("set user property")]
	HRESULT SetProp
	(
		long nCookie,
		long nProp,
		VARIANT vValue
	);

	[helpstring("get user property")]
	HRESULT GetProp
	(
		long nCookie,
		long nProp,
		[out] VARIANT * pvValue
	);
	[helpstring("close notification")]
	HRESULT Close();

	[helpstring("returns rich client info (user,computer,cookie,props)")]
	HRESULT QuerySinks2
	(
		[out] long *pDataLength,
		[out] SAFEARRAY(byte) * lpBinaryData
	);

	[helpstring("get user property 2")]
	HRESULT GetProp2
	(
		long nCookie,
		long nProp,
		[out] VARIANT * pvValue,
		[out] long * hr
	);
};

[
	object,
	pointer_default (unique),
	uuid(188cb14f-82a4-4498-87d0-ebd8d9a00fb8)
]
interface INotificationSink : IUnknown
{
	[helpstring("shared variable change notification")]
	HRESULT OnSharedVariableChange
	(
		[in] long lVarNr,
		[in] VARIANT nNewValue
	);

	[helpstring("user notification")]
	HRESULT OnNotifyUser
	(
		[in] long nOriginatorCookie,
		[in] long lEvenCode,
		[in] VARIANT * pDataVariant
	);

	[helpstring("progress notification")]
	HRESULT OnProgress
	(
		[in] long nInfoType,
		[in] long lAdvance,
		[in] long lTotal,
		[in] LPSTR lpDescription
	);
};

[
	object,
	pointer_default (unique),
	uuid(188cb168-82a4-4498-87d0-ebd8d9a00fb8)
]
interface ISupplyInfo : IUnknown
{
	[helpstring("ask object for data")]
	HRESULT AskForData
	(
		[in]  long nInfoType,
		[in]  LPCSTR lpDescription,
		[in]  VARIANT varQuestion,
		[out] VARIANT * pvarAnswer
	);
};


[
	object,
	pointer_default (unique),
	uuid(188cb16c-82a4-4498-87d0-ebd8d9a00fb8)
]
interface IPingClient : IUnknown
{
	[helpstring("test client aliveness")]
	HRESULT Ping();
};

[
	object,
	pointer_default (unique),
	uuid(188cb16d-82a4-4498-87d0-ebd8d9a00fb8)
]
interface IPingServer : IUnknown
{
	[helpstring("register client ping sink")]
	HRESULT Advise
	(
		[in] IUnknown * pPingUnknown,
		[out] long *pCookie
	);
	[helpstring("unregister client ping sink")]
	HRESULT UnAdvise
	(
		[in] long nCookie
	);
};

const long LOCKCLASS_OBJECT = 1;
const long LOCKCLASS_OPERATION = 2;

typedef struct tag_navolockid
{
	long m_class;
	long m_typeid;
	long m_idobj;
	long m_extra;
}
navolockid;

typedef enum tag_navolocktype
{
	nlt_none = 0x0000,
	nlt_exlock = 0x0001,
	nlt_shlock = 0x0002
}
navolocktype;

typedef struct tag_navolock
{
	navolocktype	m_type;
	navolockid		m_fullid;
} navolock;


[
	object,
	pointer_default (unique),
	uuid(188cb152-82a4-4498-87d0-ebd8d9a00fb8)
]
interface ILockManager : IUnknown
{
	[helpstring("advise sink")]
	HRESULT Advise
	(
		[in] LPCSTR pcUserName,
		[in] LPCSTR pcComputerName,
		[out] long * pCookie
	);

	[helpstring("unregister sink")]
	HRESULT UnAdvise
	(
		[in] long nCookie
	);

	[helpstring("(un)locks objects")]
	HRESULT Lock
	(
		[in] long nOriginatorCookie,
		[in] boolean bLock,
		[in] long nCount,
		[in, size_is(nCount)] const navolock * pNavoLock
	);

	HRESULT Lock_AddItem
	(
		[in] long iInx,
		[in] long iClass,
		[in] long iTypeid,
		[in] long iIdObj,
		[in] long iExtra,
		[in] long iLockType
	);

	HRESULT Lock2
	(
		[in] long iOriginatorCookie,
		[in] boolean bLock,
		[in] long iCount
	);
};

[
	object,
	pointer_default (unique),
	uuid(188cb17d-82a4-4498-87d0-ebd8d9a00fb8)
]
interface ICntResourceManager : IUnknown
{
	[helpstring("create resource")]
	HRESULT CreateResource
	(
		[in] LPCSTR pcResName,
		[in] long nMaxUsage
	);

	[helpstring("delete resource")]
	HRESULT DeleteResource
	(
		[in] LPCSTR pcResName
	);

	[helpstring("acquire resource")]
	HRESULT UseResource
	(
		[in] LPCSTR pcResName,
		[in] long nOriginatorCookie
	);

	[helpstring("release resource")]
	HRESULT ReleaseResource
	(
		[in] LPCSTR pcResName,
		[in] long nOriginatorCookie
	);

	[helpstring("acquire resource 2")]
	HRESULT UseResource2
	(
		[in] LPCSTR pcResName,
		[in] long nOriginatorCookie,
		[out] long * hr
	);
};


//implemented by object with backup and restore capability
[
	object,
	pointer_default (unique),
	uuid(188cb154-82a4-4498-87d0-ebd8d9a00fb8)
]
interface IBackupRestore : IUnknown
{
	[helpstring("initialize operation")]
	HRESULT Begin
	(
		[in] IUnknown * pONSinkUnknown,
		[in] boolean bBackup,
		[in] LPSTR pParameters,
		[in] ISupplyInfo * pSupplyInfo
	);
	[helpstring("finalize operation")]
	HRESULT End
	(
	);

	[helpstring("get backup stream")]
	HRESULT GetBackupStream
	(
		[out] LPSTR * ppStreamName,
		[out] LPSTR * ppStreamInfo,
		[out] IStream ** ppDataStream
	);

	[helpstring("set restore stream")]
	HRESULT SetRestoreStream
	(
		[in] LPSTR  ppStreamName,
		[in] LPSTR  ppStreamInfo,
		[in] IStream * ppDataStream,
		[in] __int64 i64Length
	);
	[helpstring("get statistics")]
	HRESULT GetStat
	(
		[out] long * pTotalCount,
		[out] long * pTotalSize
	);
};

typedef enum tag_BRSetType
{
	BRSET_INVALID = 0,
	BRSET_FILEGROUP = 1,
	BRSET_DATABASE_MSSQL = 2,
	BRSET_NAVOBRMAN = 4
} BRSetType;

const long BRMAN_PROP_PROFILE01 = 1;
const long BRMAN_PROP_PROFILE02 = 2;
const long BRMAN_PROP_PROFILE03 = 3;
const long BRMAN_PROP_PROFILE04 = 4;
const long BRMAN_PROP_PROFILE05 = 5;
const long BRMAN_PROP_PROFILE06 = 6;
const long BRMAN_PROP_PROFILE07 = 7;
const long BRMAN_PROP_PROFILE08 = 8;
const long BRMAN_PROP_PROFILE09 = 9;

//implemented by object which manages backup
[
	object,
	pointer_default (unique),
	uuid(188cb158-82a4-4498-87d0-ebd8d9a00fb8)
]
interface IBackupRestoreManager : IUnknown
{
	[helpstring("returns backup stream (pull)")]
	HRESULT GetBackupStream
	(
		[out] IStream ** ppDataStream,
		[out] IStream ** ppInfoStream,
		[in] IUnknown * pONSinkUnknown,
		[in] IUnknown * pISupplyInfo
	);
	[helpstring("sets restore stream and starts operation")]
	HRESULT SetRestoreStream
	(
		[in] IStream * pDataStream,
		[in] IStream * pInfoStream,
		[in] IUnknown * pONSinkUnknown,
		[in] IUnknown * pISupplyInfo
	);

	[helpstring("get new brset")]
	HRESULT NewBrSet
	(
		[out] IDispatch ** ppDispatch
	);
	[helpstring("add brset")]
	HRESULT AddBrSet
	(
		[in] IDispatch * pDispatch
	);

	[helpstring("remove all brsets")]
	HRESULT RemoveAllBrSets
	(
	);

	[helpstring("get enumerator")]
	HRESULT _GetNewEnum
	(
		[out] IUnknown ** ppUnknown
	);

	[helpstring("set property")]
	HRESULT SetProp
	(
		long nProp,
		VARIANT vValue
	);

	[helpstring("get property")]
	HRESULT GetProp
	(
		long nProp,
		[out] VARIANT * pvValue
	);
};

//provides streams
[
	object,
	pointer_default (unique),
	uuid(188cb155-82a4-4498-87d0-ebd8d9a00fb8)
]
interface IStreamProvider : IUnknown
{
	[helpstring("get stream on its number")]
	HRESULT Get
	(
		long  IdFile,
		[out] IStream ** pStream,
		[out] navostreaminfo * poNSI
	);
};

///////////////////////////////////////////////////////////////////////
// IStreamFilter - stream filtering interface
///////////////////////////////////////////////////////////////////////

//STF - Stream Filter Type

const long SFT_INVALID = 0;
const long SFT_STRIP_STARTING_WHITESPACE = 1;
const long SFT_COMPRESS = 2;
const long SFT_UNCOMPRESS = 3;
const long SFT_BASE64ENCODE = 4;
const long SFT_BASE64DECODE = 5;

[
	object,
	pointer_default (unique),
	uuid(188cb16b-82a4-4498-87d0-ebd8d9a00fb8)
]
interface IStreamFilter : IUnknown
{
	[helpstring("attaches input")]
	HRESULT AttachInput
	(
		[in] IStream * pInputStream
	);
	[helpstring("sets filter type")]
	HRESULT SetParam
	(
		[in] long nType
		/* expected more params */
	);
};

[
	object,
	pointer_default (unique),
	uuid(188cb177-82a4-4498-87d0-ebd8d9a00fb8)
]
interface IStreamSplitter : IUnknown
{
	[helpstring("do split")]
	HRESULT Split
	(
		[in] IStream * pInputStream,
		[in] ISupplyInfo * pSupplyInfo
	);
	[helpstring("do join")]
	HRESULT Join
	(
		[in] ISupplyInfo * pSupplyInfo
	);
};

///////////////////////////////////////////////////////////////////////
// ISimpleEnumId - simple file id enumerator
///////////////////////////////////////////////////////////////////////

[
	object,
	pointer_default (unique),
	uuid(188cb169-82a4-4498-87d0-ebd8d9a00fb8)
]
interface ISimpleEnumId : IUnknown
{
	[helpstring("retrieves next file id")]
	HRESULT Next
	(
		[out] long * pFileId
	);
	[helpstring("retrieves next file id and name")]
	HRESULT NextFull
	(
		[out] long * pFileId,
		[out] LPSTR * plpValue

	);
};


///////////////////////////////////////////////////////////////////////
//IAppDBManager - zarz¹dca "bazy danych" opisu aplikacji
///////////////////////////////////////////////////////////////////////
const long APPDBMAN_ITEMINFO_VARDEP = 0x0001;		//variable dependencies
const long APPDBMAN_ITEMINFO_MODIFDATE = 0x0002;		//modification date
const long APPDBMAN_ITEMINFO_MODIFDATE_NO_DEP = 0x0004;		//modification date without file dependencies

const long APPDBMAN_MODE_PROGRAMMER = 0x0000;
const long APPDBMAN_MODE_USER = 0x0001;

[
	object,
	pointer_default (unique),
	uuid(188cb156-82a4-4498-87d0-ebd8d9a00fb8)
]
interface IAppDBManager : IUnknown
{
	[helpstring("initializes manager for application")]
	HRESULT Init
	(
		[in] LPCSTR lpAppName		//application name
	);

	[helpstring("close notification")]
	HRESULT Close
	(
		[in] boolean bOK
	);

	[helpstring("options")]
	HRESULT SetOptions
	(
		[in] long nOptions
	);

	//generic functions
	[helpstring("adds or updates single file")]
	HRESULT Upload
	(
		[in] long IdFile,			//file id
		[in] IStream * pStream,		//input stream
		[in] LPCSTR pcExtension	//file extension (file type)
	);

	[helpstring("deletes single file")]
	HRESULT Delete
	(
		[in] long IdFile			//fileid
	);

	[helpstring("creates application")]
	HRESULT CreateApp
	(
		[in] LPCSTR lpAppName,				//application name
		[in] LPCSTR lpLocalRootDirectory,	//local story
		[in] long lKey				//uploader identification key
	);

	[helpstring("drops application")]
	HRESULT DropApp
	(
		[in] LPCSTR lpAppName				//application name
	);

	[helpstring("packs application for deployment")]
	HRESULT Pack
	(
		[in] VARIANT varDestNameOrStream,
		[in] VARIANT varDestNameOrStreamInfo
	);

	[helpstring("unpacks application for use")]
	HRESULT Unpack
	(
		[in] VARIANT varSrcNameOrStream,
		[in] VARIANT varSrcNameOrStreamInfo
	);

	[helpstring("returns simple stream enumerator")]
	HRESULT EnumFileGroup
	(
		[in]  LPCSTR lpGroupName,
		[out] ISimpleEnumId ** ppSimpleEnumFileId
	);
	[helpstring("get item informations")]
	HRESULT GetItemInfo
	(
		[in] long nInfoType,
		[in] long IdFile,			//file id
		[out] DATE * pModifDate,
		[out] long * pnVarCntr,
		[out, size_is(, *pnVarCntr)] long ** ppVarNr
	);
	[helpstring("changes operation mode")]
	HRESULT ChangeMode
	(
		[in] long nNewMode
	);
	[helpstring("returns operation mode")]
	HRESULT GetMode
	(
		[out] long * pnMode
	);
	HRESULT GetFinalStream
	(
		[in] long IdFile,
		[in] LPCSTR pcEnvironentStr,
		[out] IStream ** pStream,
		[out] navostreaminfo * poNSI
	);

	[helpstring("get item informations")]
	HRESULT GetItemInfo2
	(
		[in] long nInfoType,
		[in] long IdFile,			//file id
		[out] DATE * pModifDate,
		[out] long * pnVarCntr,
		[out] SAFEARRAY(long) * ppVarNr
	);

	[helpstring("set alternate stream provider")]
	HRESULT SetAltStreamProvider
	(
		[in] IStreamProvider * pStreamProvider
	);

};

typedef enum tag_fetchdir
{
	fdir_first,
	fdir_next,
	fdir_prev,
	fdir_last,
	fdir_abs
}
fetchdirection;

[
	object,
	pointer_default (unique),
	uuid(188cb15f-82a4-4498-87d0-ebd8d9a00fb8)
]
interface INAVOObjectCollection : IUnknown
{
	[helpstring("reads records from cursor")]
	HRESULT Fetch
	(
		fetchdirection	FetchDirection,
		[in, out] long *	nCount,
		[out] long *	pDataLength,
		[out, size_is(, *pDataLength)] byte ** lpBinaryData,
		long			nAbsolutePosition
	);
	[helpstring("returns total count of records")]
	HRESULT GetCount
	(
		[out] long * pnCount
	);
	[helpstring("refreshes recordset")]
	HRESULT Refresh
	(
		[in]  long nPositionToKeep,
		[out] long * pnCount
	);
	[helpstring("reads records from cursor")]
	HRESULT Fetch2
	(
		fetchdirection	FetchDirection,
		[in, out] long *	nCount,
		[out] long *	pDataLength,
		[out] SAFEARRAY(byte) * lpBinaryData,
		long			nAbsolutePosition
	);
};

typedef enum tag_stdobjactions
{
	action_init,

	action_insert,
	action_update,
	action_delete,
	action_get,

	action_cursor,
	action_maxid,
	action_find,
	action_candel,
	action_lists,

	action_last
}
stdobjactions;

typedef enum tag_stdobjlistoperations
{
	listop_delall,
	listop_delcollection,
	listop_save,
	listop_save2,
	listop_getid
}
stdobjlistoperations;

typedef enum tag_dbenginetype
{
	dbet_unknown,				//unknown
	dbet_ms_jet35,				//Microsoft Jet 3.5
	dbet_syb_rt55,				//Sybase SQL Anywhere Runtime 5.5
	dbet_syb_sql55,				//Sybase SQL Anywhere Standalone 5.5
	dbet_ms_sql70,				//Microsoft SQL Server 7.0
	dbet_ms_sql2000,			//Microsoft SQL Server 2000
	dbet_ibm_udb				//IBM Universal Database DB/2
}
dbenginetype;

// informacje o blob
// gdy m_FileId && m_pIStream  -> upload
// gdy m_FileId && !m_pIStream -> delete
// m_cExt - rozszerzenie nazwy pliku
typedef struct tag_transblobinfo
{
	long	m_IdParent;
	long	m_IdMapping;
	IStream * m_pIStream;
	navostreaminfo m_oNSI;
} transblobinfo;

typedef enum tag_objsrv_prop
{
	objsrv_server,
	objsrv_database,
	objsrv_user,
	objsrv_password,
	objsrv_enginetype,
	objsrv_mainuid,
}
objsrv_prop;

[
	object,
	pointer_default (unique),
	uuid(188cb15e-82a4-4498-87d0-ebd8d9a00fb8)
]
interface IObjectServer : IUnknown
{
	[helpstring("set co-managers")]
	HRESULT SetCoManagers
	(
		[in] LPCSTR pcAppName,
		[in] ILockManager * pLockManager,
		[in] long nLockManCookie,
		[in] long nOptions
	);
	[helpstring("close notification")]
	HRESULT Close
	(
		[in] boolean bOK
	);

	[helpstring("performs transaction, optionally commits")]
	HRESULT MakeTransaction
	(
		long nDataLength,
		[in, unique, size_is(nDataLength)] byte * lpBinaryData,
		long nBlobInfoCount,
		[in, unique, size_is(nBlobInfoCount)] transblobinfo * pBlobInfo,
		[in] long nWriteLockCount,
		[in, unique, size_is(nWriteLockCount)] const navolock * pNavoLock,
		[in] boolean bCommit
	);

	[helpstring("finishes transaction")]
	HRESULT FinishTransaction
	(
		[in] boolean bSuccess
	);
	[helpstring("returns requested object, only if is newer")]
	HRESULT GetObjectIfNewer
	(
		[in] long	TypeId,
		[in] long	IdObj,
		[in] long	VersionNoReturn,
		[in] boolean bWriteLock,
		[out] long *pDataLength,
		[out, size_is(, *pDataLength)] byte ** lpBinaryData
	);

	[helpstring("returns stream on ident pair")]
	HRESULT GetStream
	(
		long  IdParent,
		long  IdMapping,
		[out] IStream ** pStream,
		[out] navostreaminfo * poNSI,
		[out] long * pVersion,
		[out] long * pStreamId
	);

	[helpstring("returns unique ident for new object")]
	HRESULT GetUniqueIdent
	(
		[in] long TypeId,
		[out] long * pNewId
	);

	const long FOUNDMANY = -1;
	[helpstring("searches for specified objects")]
	HRESULT FindOnField
	(
		long		   nTypeId,
		[in] LPCSTR   lpWhereClause,
		[out] long *   pFoundId					//-1=found many, 0=not found >0=object id
	);

	[helpstring("opens regular cursor returning objects")]
	HRESULT OpenOnStatement
	(
		long TypeId,
		[in][ref] LPCSTR lpWhereClause,
		[in][ref] LPCSTR lpOrderByClause,
		[in][ref] LPCSTR lpJoinClause,
		[in] boolean bForwardOnly,
		[in] long nTop,
		[out] INAVOObjectCollection ** pCollection
	);
	[helpstring("opens Collections cursor returning ids")]
	HRESULT OpenCollection
	(
		long  CollectionId,
		long  IdParent,
		[out] long * pTotalCount,
		[out] INAVOObjectCollection ** pCollection
	);

	[helpstring("opens FTS query result collection with ids")]
	HRESULT OpenFTSQuery
	(
		long  IdMapping,
		[in][ref] LPCSTR lpQuery,
		[out] INAVOObjectCollection ** pCollection
	);

	[helpstring("opens disconected ADO recordset")]
	HRESULT OpenDiscoRecSet
	(
		[in][ref] LPCSTR lpSQLClause,
		[out] IStream ** pADORecordset,
		[out] navostreaminfo * poNSI
	);


	[helpstring("checks delete possibility")]
	HRESULT CanDelete
	(
		long			nTypeId,
		long			IdObj,
		[out] IDispatch ** pADORecordset
	);

	[helpstring("set db server option")]
	HRESULT SetProp
	(
		objsrv_prop nProp,
		VARIANT vValue
	);

	[helpstring("get db server option")]
	HRESULT GetProp
	(
		objsrv_prop nProp,
		[out] VARIANT * pvValue
	);
	[helpstring("executes SQL command")]
	HRESULT ExecSQL
	(
		[in] LPCSTR lpSQLCommand,
		[out] long * pRecordsAffected
	);

	[helpstring("sets shared variable new value")]
	HRESULT SetSharedVariable
	(
		[in] long nOriginatorCookie,	//nOriginatorCookie !=0 -> notify others
		[in] long lVarNr,
		[in] VARIANT nNewValue
	);
	[helpstring("gets shared variable value")]
	HRESULT GetSharedVariable
	(
		[in] long lVarNr,
		[out] VARIANT * pvValue
	);

	[helpstring("create extension")]
	HRESULT CreateExtension
	(
		[in] LPCSTR lpExtensionProgId,
		[out] IDispatch ** pExtensionDisp
	);

	[helpstring("write to archive")]
	HRESULT WriteToArchive
	(
		[in] LPCSTR lpSAUser,
		[in] LPCSTR lpPwd,
		[in] LPCSTR lpArchivePwd,
		[in] IStream * pDestStream
	);

	[helpstring("read from archive")]
	HRESULT ReadFromArchive
	(
		[in] LPCSTR lpSAUser,
		[in] LPCSTR lpPwd,
		[in] LPCSTR lpArchivePwd,
		[in] IStream * pSrcStream
	);


	[helpstring("performs transaction, optionally commits")]
	HRESULT MakeTransaction2
	(
		[in] SAFEARRAY(byte) * pBinaryData,
		[in] long iLockCount,
		[in] boolean bCommit,
		[in] LPCSTR lpExtras,
		[out] LPSTR * lpResult
	);

	[helpstring("returns requested object, only if is newer")]
	HRESULT GetObjectIfNewer2
	(
		[in] long	TypeId,
		[in] long	IdObj,
		[in] long	VersionNoReturn,
		[in] boolean bWriteLock,
		[out] long *pDataLength,
		[out] SAFEARRAY(byte) * lpBinaryData,
		[out] long * hr
	);

	HRESULT MakeTransaction_Stream
	(
		[in] IStream * pSrcStream,
		[in] long	IdParent,
		[in] long	IdMapping,
		[in] navostreaminfo NSI
	);

	[helpstring("opens disconected ADO recordset")]
	HRESULT OpenDiscoRecSet2
	(
		[in][ref] LPCSTR lpSQLClause,
		[out] IUnknown ** pADORecordset
	);

	[helpstring("creates connected ADO command")]
	HRESULT CreateADOCommand
	(
		[out] IUnknown ** pADOCommand
	);

	[helpstring("creates disconected ADO parameter")]
	HRESULT CreateADOParameter
	(
		[out] IUnknown ** pADOParameter
	);

	HRESULT Lock_AddItem
	(
		[in] long iInx,
		[in] long iClass,
		[in] long iTypeid,
		[in] long iIdObj,
		[in] long iExtra,
		[in] long iLockType
	);

	HRESULT PurgeCache();
};


[
	object,
	pointer_default (unique),
	uuid(188cb18d-82a4-4498-87d0-ebd8d9a00fb8)
]
interface IObjectServerExtensionHost : IUnknown
{
	[helpstring("returns database connection")]
	HRESULT GetDBConnection
	(
		[out] IUnknown ** ppDBConnection
	);

	[helpstring("lock object")]
	HRESULT Lock
	(
		[in] navolock oNavoLock
	);

	[helpstring("unlock object")]
	HRESULT UnLock
	(
		[in] navolock oNavoLock
	);


	//[helpstring("returns global store hub")]
	//HRESULT GetStoreHub
	//(
	//	[out] IDispatch ** ppNX
	//);
};

[
	object,
	pointer_default (unique),
	uuid(188cb18c-82a4-4498-87d0-ebd8d9a00fb8)
]
interface IObjectServerExtension : IUnknown
{
	[helpstring("initialization")]
	HRESULT Init
	(
		[in] IObjectServerExtensionHost * pHost
	);
};

[
	object,
	pointer_default (unique),
	uuid(188cb188-82a4-4498-87d0-ebd8d9a00fb8)
]
interface IPreprocessedDataCache : IUnknown
{
	[helpstring("get preprocessed data for file")]
	HRESULT GetData
	(
		[in] long IdFile,
		[out] IStream ** ppDataStream
	);
	[helpstring("store preprocessed data for file")]
	HRESULT PutData
	(
		[in] long IdFile,
		[in] IStream * pDataStream
	);
};


[
	object,
	pointer_default (unique),
	uuid(188cb165-82a4-4498-87d0-ebd8d9a00fb8)
]
interface IPreprocessor : IUnknown
{
	[helpstring("init")]
	HRESULT Init
	(
		[in] IDispatch * pEnvironmentDisp,
		[in] IStreamProvider * pStreamProvider,
		[in][unique] IPreprocessedDataCache * pDataCache
	);
	[helpstring("preprocess file")]
	HRESULT PreprocessFile
	(
		[in] long IdFile,
		[in] boolean bParseMode
	);
	[helpstring("get variable dependencies")]
	HRESULT GetVarDependencies
	(
		[out] long * pnVarCntr,
		[out, size_is(, *pnVarCntr)] long ** ppVarNr
	);
	[helpstring("get include dependencies")]
	HRESULT GetIncludeDependencies
	(
		[out] long * pnFileCntr,
		[out, size_is(, *pnFileCntr)] long ** ppIdFile
	);

	[helpstring("close preprocessor")]
	HRESULT Close
	(
	);
};


[
	object,
	pointer_default (unique),
	uuid(188cb15b-82a4-4498-87d0-ebd8d9a00fb8)
]
interface ICachedData : IUnknown
{
	[helpstring("close notification")]
	HRESULT Close
	(
		[in] boolean bOK
	);

	[helpstring("get item information")]
	HRESULT GetItem
	(
		[in] long IdFile,
		[in] LPCSTR lpFullServerPath,
		[in] long DescriptorLength,
		[unique, in, size_is(DescriptorLength)] byte * lpDescriptor,
		[out] IStream ** ppDataStream,
		[out] navostreaminfo * poNSI
	);
	[helpstring("stores item and information")]
	HRESULT StoreItem
	(
		[in] long IdFile,
		[in] LPCSTR lpFullServerPath,
		[in] long DescriptorLength,
		[unique, in, size_is(DescriptorLength)] byte * lpDescriptor,
		[in] long TransactionId,
		[in] navostreaminfo * poNSI,
		[out] IStream ** ppDataStream
	);

	[helpstring("deletes item and information")]
	HRESULT RemoveItem
	(
		[in] long IdFile,
		[in] LPCSTR lpFullServerPath,
		[in] long DescriptorLength,
		[unique, in, size_is(DescriptorLength)] byte * lpDescriptor,
		[in] long TransactionId
	);

	[helpstring("begin transaction")]
	HRESULT BeginTransaction
	(
		[out] long * pTransacionId
	);
	[helpstring("finishes transaction")]
	HRESULT FinishTransaction
	(
		[in] long TransactionId,
		[in] boolean bSuccess
	);

	[helpstring("purge cache")]
	HRESULT Purge
	(
		[in] LPCSTR lpFullServerPath
	);

	[helpstring("returns unique ident for new object")]
	HRESULT GetUniqueIdent
	(
		[in, out] long * pNewId
	);

	[helpstring("returns GUID for cache info")]
	HRESULT GetCacheInfoGUID
	(
		[in] LPCSTR lpFullServerPath,
		[out] GUID * pGUID
	);
	[helpstring("makes FTS query")]
	HRESULT FTSQuery
	(
		[in] LPCSTR lpFullServerPath,
		[in] LPCSTR lpQuery,
		[out] ISimpleEnumId ** ppSimpleEnumFileId
	);
	[helpstring("options")]
	HRESULT SetOptions
	(
		[in] long nOptions
	);
	[helpstring("store data object")]
	HRESULT StoreDataObject
	(
		[in] LPCSTR lpFullServerPath,
		[in] long nTypeId,
		[in] long nIdObj,
		[in] long nVersion,
		[in] long nDataLength,
		[unique, in, size_is(nDataLength)] byte * pData
	);
	[helpstring("get data object")]
	HRESULT RetrieveDataObject
	(
		[in] LPCSTR lpFullServerPath,
		[in] long nTypeId,
		[in] long nIdObj,
		[in] long nVersion,
		[out] long *pDataLength,
		[out, size_is(, *pDataLength)] byte ** ppData
	);

	[helpstring("write to archive")]
	HRESULT WriteToArchive
	(
		[in] LPCSTR lpFullServerPath,
		[in] IStream * pDestStream
	);

	[helpstring("read from archive")]
	HRESULT ReadFromArchive
	(
		[in] LPCSTR lpFullServerPath,
		[in] IStream * pSrcStream
	);
};


typedef enum tag_navoservicetype
{
	nst_notman,
	nst_lockman,
	nst_appdb,
	nst_brman,
	nst_objserver
} navoservicetype;



[
	object,
	pointer_default (unique),
	uuid(188cb162-82a4-4498-87d0-ebd8d9a00fb8)
]
interface IServerClient : IUnknown
{
	[helpstring("returns specific service pointer")]
	HRESULT GetService
	(
		[in] navoservicetype eNST,
		[out] IUnknown ** ppUnknown
	);
	[helpstring("returns newer version streams")]
	HRESULT GetUpdateVersionIfNewer
	(
		[in]  long nUpdateType,
		[in]  LPCSTR lpClientVersion,
		[out] IStream ** ppDataStream,
		[out] IStream ** ppInfoStream
	);

	[helpstring("advise lock manager")]
	HRESULT AdviseLM
	(
		[in] LPCSTR pcUserName,
		[in] LPCSTR pcComputerName,
		[out] long * pCookie
	);

	[helpstring("unadvise lock manager")]
	HRESULT UnAdviseLM
	(
		[in] long nCookie
	);
	[helpstring("register notification sink")]
	HRESULT AdviseNM
	(
		[in] IUnknown * pONSinkUnknown,
		[in] LPCSTR pcUserName,
		[in] LPCSTR pcComputerName,
		[in] notifysinkclass eNSC,
		[out] long *pCookie
	);
	[helpstring("unregister notification sink")]
	HRESULT UnAdviseNM
	(
		[in] long nCookie
	);
	[helpstring("reads string registry value from server")]
	HRESULT GetRegistryKeyString
	(
		[in] long hKeyClass,
		[in] LPCSTR lpSubKey,
		[in] LPCSTR lpName,
		[out] LPSTR * plpValue
	);
	[helpstring("writes string registry value from server")]
	HRESULT SetRegistryKeyString
	(
		[in] long hKeyClass,
		[in] LPCSTR lpSubKey,
		[in] LPCSTR lpName,
		[in] LPCSTR lpValue
	);
	[helpstring("writes string registry entries from server")]
	HRESULT EnumRegistryKeys
	(
		[in] long hKeyClass,
		[in] LPCSTR lpSubKey,
		[out] LPSTR * plpValue
	);
	[helpstring("writes string registry value from server")]
	HRESULT GetUniqueId
	(
		[out] LPSTR * ppUniqueId
	);

	[helpstring("close")]
	HRESULT Close2();
};

[
	object,
	pointer_default (unique),
	uuid(188cb162-2012-4499-87d0-ebd8d9a00fb8)
]
interface IServerClientFactory : IUnknown
{
	HRESULT GetServerClient
	(
		[in]  LPCSTR lpServerName,
		[in]  LPCSTR lpAppID,
		[out] IServerClient ** ppServerClient
	);
}

[
	object,
	pointer_default (unique),
	uuid(188cb181-82a4-4498-87d0-ebd8d9a00fb8)
]
interface ICrossInfoManager : IUnknown
{
	[helpstring("set user property")]
	HRESULT SetProp
	(
		[in, out] long *	pnUserCookie,
		[in] long nProp,
		[in] VARIANT * pvValue
	);

	[helpstring("get user property")]
	HRESULT GetProp
	(
		long nUserCookie,
		long nProp,
		[out] VARIANT * pvValue
	);
	[helpstring("delete user")]
	HRESULT DeleteUser
	(
		long nUserCookie
	);
};

[
	object,
	pointer_default (unique),
	uuid(188cb184-82a4-4498-87d0-ebd8d9a00fb8)
]
interface IVirtualMachine : IUnknown
{
	[helpstring("load binary code")]
	HRESULT Load
	(
		[in] IStream * pSrcStream
	);
	[helpstring("initializes machine")]
	HRESULT Init
	(
	);
	[helpstring("returns program object")]
	HRESULT GetProgramObject
	(
		[out] IDispatch ** ppProgramObject
	);
};

[
	object,
	pointer_default (unique),
	uuid(188cb182-82a4-4498-87d0-ebd8d9a00fb8)
]
interface IScriptCompiler : IUnknown
{
	[helpstring("set input source code")]
	HRESULT SetSourceText
	(
		[in] LPCSTR pcSourceText
	);
	[helpstring("declare external ident")]
	HRESULT DeclareIdent
	(
		[in] LPCSTR pcIdentName
	);
	[helpstring("perform compilation")]
	HRESULT Compile
	(
	);
	[helpstring("get line begin")]
	HRESULT GetLine
	(
		[in] long nLineNr,
		[out] long *pLineBegin
	);

	[helpstring("save as binary code")]
	HRESULT Save
	(
		[in] IStream * pDestStream
	);
	[helpstring("creates virtual machine")]
	HRESULT GetVirtualMachine
	(
		[out] IVirtualMachine ** ppVirtualMachine
	);
	[helpstring("set property")]
	HRESULT SetProp
	(
		long nProp,
		VARIANT vValue
	);
};

interface INEDataObjectList;

[
	object,
	local,
	pointer_default (unique),
	uuid(188cb191-82a4-5000-87d0-ebd8d9a00fb8)
]
interface INEDataObject : IUnknown
{
	long get_typeid();
	long get_idobj();
	long get_i4_field(long nFieldnr);
	BSTR get_bstr_field(long nFieldNr);
	CY get_cy_field(long nFieldNr);
	DATE get_date_field(long nFieldNr);
	INEDataObject * get_obj_field(long nFieldNr);
	INEDataObjectList * get_list_field(long nFieldNr);
};

[
	object,
	local,
	pointer_default (unique),
	uuid(188cb192-82a4-5000-87d0-ebd8d9a00fb8)
]
interface INEDataObjectList : IUnknown
{
	[helpstring("set property")]
	HRESULT SetProp
	(
		long nProp,
		VARIANT vValue
	);
};

[
	object,
	local,
	pointer_default (unique),
	uuid(188cb193-82a4-5000-87d0-ebd8d9a00fb8)
]
interface INEDataTransaction : IUnknown
{
	[helpstring("set property")]
	HRESULT SetProp
	(
		long nProp,
		VARIANT vValue
	);
};

interface INUIContainer;

[
	object,
	local,
	pointer_default (unique),
	uuid(188cb1b1-82a4-4498-87d0-ebd8d9a00fb8)
]
interface INUIElement : IUnknown
{
	long get_ident();

	boolean get_disable();
	void set_disable(boolean bDisable);

	boolean get_hide();
	void set_hide(boolean bHide);

	long get_backcolor();
	void set_backcolor(long nBackColor);

	long get_backcolor2();
	void set_backcolor2(long nBackColor);

	long get_forecolor();
	void set_forecolor(long nForeColor);

	boolean get_focus();
	void set_focus(boolean bFocus);

	INUIContainer * get_container();
};

[
	object,
	local,
	pointer_default (unique),
	uuid(188cb1b2-82a4-4498-87d0-ebd8d9a00fb8)
]
interface INUIContainer : INUIElement
{
	INUIElement * get_element(long nOuterPos);
};

[
	uuid(188cb151-82a4-4498-87d0-ebd8d9a00fb8)
]
library NE2002Iface
{
	interface INavoErrorInfo;
	interface INotificationManager;
	interface INotificationSink;
	interface ISupplyInfo;
	interface ILockManager;
	interface IBackupRestore;
	interface IStreamProvider;
	interface IAppDBManager;
	interface IBackupRestoreManager;
	interface INAVOObjectCollection;
	interface INavoObjManager;
	interface IPreprocessor;
	interface ICachedData;
	interface ISimpleEnumId;
	interface IStreamFilter;
	interface IPingClient;
	interface IPingServer;
	interface IServerClient;
	interface IServerClientFactory;
	interface IStreamSplitter;
	interface ICntResourceManager;
	interface ICrossInfoManager;
	interface IScriptCompiler;
	interface IVirtualMachine;
	interface IObjectServer;

	interface IObjectServerExtension;
	interface IObjectServerExtensionHost;

	interface INEDataObject;

	interface INUIElement;
	interface INUIContainer;
};
