#define CTRL_TYPE_STATIC		0
#define CTRL_TYPE_BUTTON		1
#define CTRL_TYPE_EDIT			2
#define CTRL_TYPE_MULTILINE		3
#define CTRL_TYPE_DATE			4
#define CTRL_TYPE_CURRENCY		5
#define CTRL_TYPE_RADIO			6
#define CTRL_TYPE_CHECKBOX		7
#define CTRL_TYPE_TIME			8


#define CTRL_TYPE_PARAGRAPH		10
#define CTRL_TYPE_BREAKLINE		11
#define CTRL_TYPE_BREAKPAGE		12
#define CTRL_TYPE_TREE			13
#define CTRL_TYPE_RICHEDIT		14
#define CTRL_TYPE_WEB			15
#define CTRL_TYPE_OLECONTROL	16
#define CTRL_TYPE_PICTURE		17
#define CTRL_TYPE_EXTERN		18

#define CTRL_TYPE_PAGEMAN		20
#define CTRL_TYPE_TABLECELL		21
#define CTRL_TYPE_TABLEROW		22

#define CTRL_TYPE_TABLE			24
#define CTRL_TYPE_GRID			25
#define CTRL_TYPE_STATICEX		26



#define CTRL_TYPE_DOCUMENTOBJECT 29
#define CTRL_TYPE_TOPLEVELPAGE	30
#define CTRL_TYPE_TABMANAGER	31
#define CTRL_TYPE_TABITEM		32
#define CTRL_TYPE_HSCROLL		33
#define CTRL_TYPE_VSCROLL		34
#define CTRL_TYPE_INTEDIT		35

