/*
	NAVO Sp. z o.o. (2001)
	
	NAVO Enterprise

	internal engine commands
*/

//internal

#define CMD_INTERNAL_GOBACK				9002
#define CMD_INTERNAL_ARENA_CLICK		9003
#define CMD_INTERNAL_USER_NOTIFY		9004

//CMD_INTERNAL_ACTIVATE					9005

#define CMD_INTERNAL_MINIMIZE			9006
#define CMD_INTERNAL_APPLYCTRLDATA		9007
#define CMD_INTERNAL_NEW_ERROR			9008

#define INTERNALVAR_USER_NOTIF_ORIG		5001
#define INTERNALVAR_USER_NOTIF_EVENT	5002
#define INTERNALVAR_USER_NOTIF_VALUE	5003

#define INTERNALVAR_NEWERROR_ERRORCODE	5000
#define INTERNALVAR_NEWERROR_HELPID		5001
#define INTERNALVAR_NEWERROR_ERRORSTR	5002


#define GVAR_CONTROL_VERB_INTERNAL		5010


#define INTERNALVAR_ARENA_CLICK_BUTTON	5001


#define PROP_FCONTROL_OPERATION			1

#define FCONTROL_OPERATION_DATE_TODAY		1
#define FCONTROL_OPERATION_DATE_CALENDAR	2