/*
	NAVO Sp. z o.o. (2001)
	
	NAVO Enterprise

	stderrorcode.h

	standard error codes

*/

//{{NO_DEPENDENCIES}}

//commonly used error-codes
enum errorcode
{
	ERCO_OK									= 1000,
	ERCO_NOTAVAILABLE						= 1010,
	ERCO_GENERAL							= 1011,
	ERCO_TODO								= 1012,
	ERCO_MFC_EXCEPTION						= 1013,
	ERCO_NOT_ENOUGH_RIGHTS					= 1014,
	ERCO_GENERAL_DETAILS					= 1019,

	ERCO_CANNOT_CREATE_NXM_CLIENT			= 1020,

	ERCO_OBJ_DOESNT_IMPLEMENT_INTERFACE		= 1100,
	ERCO_QUERY_INTERFACE_FAILED				= 1101,
	ERCO_NAVOTHREAD_OLE_INIT_FAILED			= 1102,
	ERCO_ERRORINFO_RETRIEVE_ERROR_FAILED	= 1103,
	ERCO_ERRORINFO_NO_INFO_AVAILABLE		= 1104,
	ERCO_USER_BROKEN_ACTION					= 1105,
	ERCO_USER_MESSAGE						= 1106,
	
	ERCO_SCP_CREATEINSTANCE_FAIL			= 1201,
	ERCO_SCP_CREATEINSTANCE_FAIL2			= 1202,
	ERCO_SCP_CREATEINSTANCE_FAIL3			= 1203,
	ERCO_UNABLE_TO_MARSHAL_ITNERF_TO_STREAM	= 1204,
	ERCO_UNABLE_TO_MARSHAL_ITERF_FROM_STREAM= 1205,
	ERCO_CREATING_THREAD_FAILED				= 1206,
	ERCO_NAVOOLEDATASRC_BADSTREAM			= 1207,
	ERCO_NAVOOLEDATASRC_CANTREGFORMAT		= 1208,
	ERCO_MUTEX_CREATION_FAILED				= 1209,
	ERCO_CREATEPROCESSFAILED				= 1210,

	ERCO_PINGSERVER_ADVISE_FAILED			= 1220,
	ERCO_PINGSERVER_UNADVISE_FAILED			= 1221,

	ERCO_GENERICCOMERROR					= 1300,
	ERCO_INSIDE_AUTOMATION_FAULT			= 1301,

	ERCO_SOV_NOMEMORY					 = 1320,
	ERCO_SOV_BADTYPE					 = 1321,
	ERCO_SOV_CANNOTCHANGETYPE			 = 1322,
	ERCO_INTERNAL_REGEXCEPTION			 = 1323,
	ERCO_INTERNAL_DLLLOADFAILED			 = 1324,
	ERCO_INTERNAL_REGISTERMODULEFAILED	 = 1325,
	ERCO_INTERNAL_UNREGISTERMODULEFAILED = 1326,
	ERCO_INTERNAL_LOADFUNCTIONFAILED	 = 1327,
	ERCO_INTERNAL_UNKNOWNERROR			 = 1328,
	ERCO_NOT_ENOUGH_MEMORY_IN_BSTR		 = 1329,

	ERCO_UNABLE_TO_REGIST_CLASS_FACTORY	 = 1330,
	ERCO_UNABLE_TO_REVOKE_CLASS_OBJ		 = 1331,
	ERCO_UNABLE_TO_REGIST_SERVER		 = 1332,
	ERCO_UNABLE_TO_UNREGIST_SERVER		 = 1333,
	ERCO_COPY_ENGINE_FILES_FAILED		 = 1334,
	ERCO_UPDATE_ENGINE_VERSION_FAILED	 = 1335,
	ERCO_CLIENT_ENGINE_VERSION_NEWER	 = 1336,

	ERCO_LOCK_IMPOSS_BECAUSE_OTHERS		= 1450,
	ERCO_LOCK_ALREADY_HAS_READ_LOCK		= 1451,
	ERCO_LOCK_ALREADY_HAS_WRITE_LOCK	= 1452,
	ERCO_LOCK_NO_READ_LOCK_TO_FREE		= 1453,
	ERCO_LOCK_NO_WRITE_LOCK_TO_FREE		= 1454,

	ERCO_UNABLE_TO_WRITE_ALL_TO_STREAM  = 1478,
	ERCO_UNABLETOSETCURRENTDIRECTORY	= 1479,
	ERCO_UNABLE_TO_READ_FROM_STREAM		= 1480,
	ERCO_UNABLE_TO_SEEK_IN_STREAM		= 1481,
	ERCO_UNABLE_TO_GET_STREAM_INFO		= 1482,
	ERCO_UNABLE_TO_WRITE_TO_STREAM		= 1483,
	ERCO_CREATESTREAMONHGLOBAL_FAILED	= 1484,
	ERCO_UNABLE_TO_OPEN_STREAM			= 1485,
	ERCO_UNABLETOGETCURRENTDIRECTORY	= 1486,
	/*	= 1487,*/
	ERCO_ISTREAM_SEEK_FaILED			= 1488,
	ERCO_UNABLE_TO_OPEN_FILE			= 1489,
	ERCO_UNABLE_TO_CREATE_DIRECTORY		= 1490,
	ERCO_UNABLE_TO_DELETE_DIRECTORY		= 1491,
	ERCO_GETTEMPPATH_FAILED				= 1492,
	ERCO_GETFULLPATHNAME_FAILURE		= 1493,
	/* = 1494,*/
	ERCO_UNABLE_TO_GET_STREAM_SIZE		= 1495,
	ERCO_FUN_CHANGED_REF_ARGS_TYPE		= 1496,
	ERCO_INVOKE_FAILED					= 1497,
	//bez stringów - end

	ERCO_STRM_FLTR_COMPRESS_READ_FAIL	= 1498,
	ERCO_STRM_FLTR_UNCOMPRESS_READ_FAIL	= 1499,
	ERCO_STRM_FLTR_SSW_READ_FAIL		= 1500,
	ERCO_STRM_OBJ_NO_STREAM				= 1501,
	ERCO_STRM_FLTR_BASE64EN_READ_FAIL	= 1502,
	ERCO_STRM_FLTR_BASE64DE_READ_FAIL	= 1503,


	ERCO_SET_METHOD_NOT_ALLOWED			= 1520,
	ERCO_GET_METHOD_NOT_ALLOWED			= 1521,
	ERCO_FUNCTION_NAME_NOT_FOUND		= 1522,
	ERCO_ERROR_IN_OLEDATE2PARAM			= 1523,
	ERCO_SAVESTREAMTOFILE_FAILED		= 1524,
	ERCO_INET_UPLOAD_ERROR				= 1525,

	ERCO_SETSCRIPTSITE_FAILED			= 1570,
	ERCO_SCRIPT_INIT_FAILED				= 1571,
	ERCO_SCRIPTENGINE_PARSINGFAILED		= 1572,
	ERCO_SETSCRIPTSTATE_FAILED			= 1573,
	ERCO_GETSCRIPTDISPATCH_FAILED		= 1574,
	ERCO_SCRIPTENGINE_ADDNAMEFAILED		= 1575,
	ERCO_SCRIPT_INVOKE_FAILED			= 1576,

	ERCO_SVENV_VARIABLEDOESNOTEXISTS	= 1577,

	ERCO_PARSING_INTERNAL				= 1600,
	ERCO_PARSE_EXPECTED_SOMETHING_ELSE	= 1601,
	ERCO_PARSE_ONLY_ONCE				= 1602,
	ERCO_PARSE_VALUE_UNEXPECTED			= 1603,
	ERCO_PARSE_NEWFIELD_UNEXPECTED		= 1604,
	ERCO_PARSE_BAD_TYPEID				= 1605,
	ERCO_PARSE_MISSING_TYPEID			= 1606,
	ERCO_PARSE_BAD_ELEMENT_IDENT		= 1607,
	ERCO_PARSE_FIELD_NOT_FOUND			= 1608,
	ERCO_PARSE_MODE_IS_REQUIRED			= 1609,
	ERCO_PARSE_INVALID_MODE				= 1610,
	ERCO_PARSE_SYNTAX_ERROR				= 1611,
	ERCO_PARSE_SYNTAX_ERROR_WITHINFO	= 1612,
	ERCO_PARSE_BAD_CHAR_WIDTH_VALUE		= 1613,

	ERCO_PREP_UNABLE_TO_OPEN_INPUTFILE	= 1650,
	ERCO_PREP_UNKNOWN_DIRECTIVE			= 1651,
	ERCO_PREP_UNEXPECTED_EOL			= 1652,
	ERCO_PREP_INVALID_IDENTIFIER		= 1653,
	ERCO_PREP_ALREADY_DEFINED			= 1654,
	ERCO_PREP_EOL_EXPECTED				= 1655,
	ERCO_PREP_UNDEF_NOT_DEFINED			= 1656,
	ERCO_PREP_UNEXPECTED_ENDIF			= 1657,
	ERCO_PREP_UNEXPECTED_ELSE			= 1658,
	ERCO_PREP_EXPECTED_QUOTE			= 1659,
	ERCO_PREP_RECURSIVE_INCLUDE			= 1660,
	ERCO_PREP_LINE_TOO_LONG				= 1661,
	ERCO_PREP_IF_EVAL_FAILED			= 1662,
	ERCO_PREP_EXPECTED                  = 1663,

	ERCO_HYPERLINK_GETVAR_NOTEXISTS		= 1670,
	ERCO_READHLI_PROP_ALREADY_DEFINED	= 1671,
	ERCO_READHLI_PROP_VAL_DOESNT_AGREE_WITH_TYPE = 1672,
	ERCO_READHLI_VARIABLE_EXPECTED		= 1673,

	ERCO_PERIF_COM_CANT_OPEN_PORT		= 1850,
	ERCO_PERIF_COM_CANT_INIT_PORT		= 1851,
	ERCO_PERIF_COM_WRITE_FAILED			= 1852,
	ERCO_PERIF_COM_WRITE_FAILED2		= 1853,
	ERCO_PERIF_COM_READ_FAILED			= 1854,
	ERCO_PERIF_COM_READ_FAILED2			= 1855,
	ERCO_PERIF_COM_CANT_SET_TIMEOUTS	= 1856,
	ERCO_PERIF_COM_INVOKE_FAILED		= 1857,
	ERCO_PERIF_COM_WRITESTR_INV_PARAM	= 1858,
	ERCO_PERIF_COM_WRITE_INV_VALUE		= 1859,

	ERCO_BRMAN_PREPARE_BACKUP_FAILED	= 1880,
	ERCO_BRMAN_RESTORE_DB_IN_USE		= 1881,
	ERCO_BRMAN_RESTORE_FAILED			= 1882,
	ERCO_BRMAN_BACKUP_FAILED			= 1883,
	ERCO_BRMANCTRL_COPYING_FAILED		= 1887,

	ERCO_OBJSERV_COMMIT_FAILED				= 1900,
	ERCO_OBJSERV_ADDPARAM_FAILED			= 1901,
	ERCO_OBJSERV_GETOBJ_NO_OBJECT			= 1902,
	ERCO_OBJSERV_UNABLE_TO_INIT_SECURITY	= 1903,
	ERCO_OBJSERV_GETUIQID_FILE				= 1904,
	ERCO_OBJSERV_SINGLE_LOCK_FAILED			= 1905,
	ERCO_OBJSERV_GETFILE_FAILED				= 1906,
	ERCO_OBJSERV_STOREFILE_FAILED			= 1907,
	ERCO_OBJSERV_STOREFILE_FAILED2			= 1908,
	ERCO_OBJSERV_DELETEFILE_FAILED			= 1909,
	ERCO_OBJSERV_ADDPARAM_INVALID_TYPE		= 1910,
	ERCO_OBJSERV_BEGIN_FILE_TRANS_FAILED	= 1911,
	ERCO_OBJSERV_GET_CACHE_GUID_FAILED		= 1912,
	ERCO_OBJSERV_CACHE_GUID_MISMATCH		= 1913,
	ERCO_OBJSERV_CACHE_GUID_MISSING_INDB	= 1914,
	ERCO_OBJSERV_CACHE_MISSING_IN_CACHE		= 1915,

	
	ERCO_NOM_UNLOCK_FAILED			= 1990,
	ERCO_NOM_WRITE_LOCK_FAILED		= 1991,
	ERCO_NOM_WRITE_UNLOCKS_FAILED	= 1992,

	ERCO_STDOBJ_CANNOT_DEL_NEWOBJ		 = 1994,
	ERCO_STDOBJ_FIELD_MUST_UNIQUE		 = 1995,
	ERCO_STDOBJ_CANNOT_GET_WRITE_LOCK	 = 1996,
	ERCO_STDOBJ_FIELD_MUST_BE_NONEMPTY	 = 1997,
	ERCO_STDOBJ_CANNOT_GET_READ_LOCK	 = 1998,
	ERCO_STDOBJ_CANNOT_READ_NOT_INITED	 = 1999,
	ERCO_STDOBJ_INVALID_FIELD_NR		 = 2000,
	ERCO_STDOBJ_SET_NOT_ALLOWED			 = 2001,
	ERCO_STDOBJ_REF_MUST_BE_DISP_OR_LONG = 2002,
	ERCO_STDOBJ_CANNOT_CHANGE_FIELD_TYPE = 2003,
	ERCO_STDOBJ_REF_TO_ANOTHER_TYPE		 = 2004,
	ERCO_STDOBJ_INVALID_VALUE_FOR_FIELD  = 2005,
	ERCO_STDOBJ_HAS_NO_PARENT			 = 2006,
	ERCO_STDOBJ_EXCEED_FIELD_MAXLEN		 = 2007,
	ERCO_STDOBJ_REF_IS_REQUIRED			 = 2008,
	ERCO_STDOBJ_CANNOT_DEL_OBJ_IS_USED	 = 2009,
	ERCO_STDOBJ_RECURSION_IN_RECALC		 = 2010,

	ERCO_STDOBJ_CANNOT_MARK_F_D_CHILD	 = 2011,
	ERCO_STDOBJLIST_INSERTNEW_BAD_INDEX  = 2012,
	ERCO_STDOBJLIST_REMOVE_BAD_INDEX	 = 2013,
	ERCO_STDOBJLIST_GET_BAD_INDEX		 = 2014,
	ERCO_STDOBJLIST_FIND_NOT_STDOBJ		 = 2015,
	ERCO_STDOBJLIST_ELEMENT_MARKED_FOR_DEL=2016,
	ERCO_STDOBJLIST_INSERTNEW_DISALLOWED = 2017,
	ERCO_STDOBJLIST_ADDNEW_DISALLOWED	 = 2018,
	ERCO_STDOBJLIST_REMOVE_DISALLOWED	 = 2019,

	ERCO_STDOBJ_EXCEED_ENUM_VALUE		 = 2020,
	ERCO_STDOBJ_TRIGGER_MUST_RET_BOOL	 = 2021,
	ERCO_STDOBJ_RECALC_MUST_RET_BOOL	 = 2022,
	ERCO_STDOBJ_CANNOT_SET_OLDVAL		 = 2023,
	ERCO_STDOBJ_CANNOT_IGNORE_OLD		 = 2024,

	ERCO_LOAD_PICTURE_BAD_SOV			 = 2030,
	
	ERCO_TREEXML_UNABLE_LOAD			 = 2100,
	ERCO_TREEXML_NO_ROOT				 = 2101,
	ERCO_TREEXML_NO_SUCH_NODE			 = 2102,
	ERCO_TREEXML_UNABLE_TO_GET_CHILDREN  = 2103,
	ERCO_TREEXML_UNABLE_TO_GET_CHILDCNT	 = 2104,
	ERCO_TREEXML_UNABLE_TO_GET_ITEM		 = 2105,
	ERCO_TREEXML_UNABLE_TO_GET_NODENAME	 = 2106,

	ERCO_CURCOL_TO_LATE_CHANGED_FORWARONLY=2110,
	ERCO_CURCOL_FORWARONLY				 = 2111,
	ERCO_CURCOL_GET_BAD_INDEX			 = 2112,
	ERCO_CURCOL_TO_LATE_SET_TOP			 = 2113,
	
	ERCO_SOD_UNAVAILABLE				 = 2130,
	ERCO_SOD_GETFIELD_FAILED			 = 2131,
	ERCO_SOFD_INVALID_SQLTYPE			 = 2132,
	ERCO_SOFD_REFTYPE_NA_FOR_THIS_FIELD	 = 2133,
	ERCO_SOFD_WILDREF_TO_LESS_TYPEIDS	 = 2134,
	ERCO_SOD_GETCURSOR_FAILED			 = 2135,
	ERCO_SOFD_ENUM_TO_LESS_ITEMS		 = 2136,

	ERCO_IMAGE_NOT_AVAILABLE			 = 2390,

	ERCO_COMPRESSION_FAILED				 = 2395,
	ERCO_DECOMPRESSION_FAILED			 = 2396,
	ERCO_DEFMAN_ADDSOF_FAILED			 = 2397,
	ERCO_DEFMAN_INVALID_ARCHIVE_VERSION	 = 2398,

	ERCO_VIRTTRANS_GETOBJ_IDOBJZERO		= 2400,
	ERCO_VIRTTRANS_GETOBJ_FAILED		= 2401,
	ERCO_VIRTTRANS_SAVE_FAILED			= 2402,
	ERCO_VIRTTRANS_SAVE_NOTNECCESSARY	= 2403,
	ERCO_VIRTTRANS_NO_TRANSACTION		= 2404,
	ERCO_VIRTTRANS_NO_VARIABLE			= 2405,
	ERCO_VIRTTRANS_DESTROING_IN_CHAIN	= 2406,
	ERCO_OBJCOOR_NO_VARIABLE			= 2407,

	ERCO_UIELEM_SETPROP_NOT_ALLOWED		= 2450,
	ERCO_UIELEM_GETPROP_NOT_EXISTS		= 2451,
	
	ERCO_UITABLE_TRANSFER_REQUIRED		= 2452,
	ERCO_UITABLE_BAD_ROW_IN_GETCELL		= 2453,
	ERCO_UITABLE_BAD_COL_IN_GETCELL		= 2454,
	ERCO_UITABLE_ONLY_ONE_PATTERN		= 2455,
	ERCO_UITABLE_BAD_ROW_NR				= 2456,
	ERCO_UITABLE_BAD_COL_NR				= 2457,
	ERCO_UITABLE_BAD_COL_NR_INTERNAL	= 2458,
	
	ERCO_UIOPTION_OUT_OF_RANGE			= 2465,
	
	ERCO_PAGEMAN_DUPLICATE_IDENT		= 2499,
	ERCO_PAGEMAN_NO_ELEMENT				= 2500,
	ERCO_PAGEMAN_BAD_VERT_MARGIN		= 2501,

	ERCO_APPDB_INVALIDFILEID			= 2520,
	ERCO_APPDB_FORBIDDENINUSERMODE		= 2521,
	ERCO_APPDB_FORBIDDENINPROGRMODE		= 2522,
	ERCO_APPDB_NOT_INITED				= 2523,
	ERCO_APPDB_ERROR_IN_STDOBJDEF		= 2524,
	ERCO_APPDB_MISSING_IN_REGISTRY		= 2525,
	ERCO_APPDB_UNBL_TO_OPEN_FILEINFO	= 2526,
	ERCO_APPDB_UNBL_TO_OPEN_APPFILE		= 2527,
	ERCO_APPDB_FILEINFO_BAD_VERSION		= 2528,
	ERCO_APPDB_FILEINFO_VERSION_MISMATCH= 2529,
	ERCO_APPDB_NO_VARDEP_INFO			= 2530,
	ERCO_APPDB_PREP_VARDEP_FAILED		= 2531,
	ERCO_APPDB_PREP_FAILED				= 2532,
	ERCO_APPDB_PREP_FAILED2				= 2533,
	ERCO_APPDB_ENUM_DATAOBJ				= 2534,

	ERCO_PAGE_OPENING_WITH_NON_EXISTING_OBJ = 2550,
	ERCO_PAGE_OPENING_PARSING_ERROR			= 2551,
	ERCO_PAGE_CANNOT_PASTE_THIS_DATA	= 2552,

	ERCO_FONTHOLDER_UNABLE_TO_INIT		 = 2569,
	
	ERCO_STYLEPARSER_MISSING_ITEM_NAME	 = 2570,
	
	ERCO_STYLEPROV_INVALID_FONT_SIZE	 = 2580,
	ERCO_STYLEPROV_CANNOT_CREATE_FONT	 = 2581,
	ERCO_STYLEPROV_NO_STYLE				 = 2582,
	ERCO_STYLEPROV_NO_ELEMENT_WITH_INX	 = 2583,
	
	ERCO_VIRTKEY_BAD_SHORTKEY			 = 2592,
	ERCO_VIRTKEY_BAD_KEYCODE_DESCRIPTION = 2591,

	ERCO_EXCHLOG_FUN_FAILED_DATAENTERED	 = 2600,
	ERCO_EXCHLOG_FUN_FAILED_GETDATA		 = 2601,	
	ERCO_EXCHLOG_FUN_FAILED_NEEDCHILDREN = 2602,
	ERCO_EXCHLOG_FUN_FAILED_INSERTROW	 = 2603,
	ERCO_EXCHLOG_FUN_FAILED_DELETEROW	 = 2604,
	ERCO_EXCHLOG_FUN_FAILED_OLECTRLEVENT = 2605,
	ERCO_EXCHLOG_FUN_FAILED_RIGHTCLICK	 = 2606,
	ERCO_EXCHLOG_FUN_FAILED_GOTLOSTFOCUS = 2607,


	ERCO_USERDOC_MISSING_GVAR_CMD			=2620,
	ERCO_USERDOC_CANNOT_OPEN_CLASSDEF		=2621,
	ERCO_USERDOC_CANNOT_CREATE_MAIN_WINDOW	=2622,
	ERCO_USERDOC_CANNOT_INIT_APPDB			=2623,
	ERCO_USERDOC_CANNOT_CREATE_APPDB		=2624,
	ERCO_USERDOC_CANNOT_CREATE_OBJECTSERVER	=2625,
	ERCO_USERDOC_CANNOT_CREATE_LOCKMANAGER	=2626,
	ERCO_USERDOC_LOCKMANAGER_ADVISE_FAILED	=2627,
	ERCO_USERDOC_CANNOT_CREATE_NOTIFMANAGER	=2628,
	ERCO_USERDOC_NOTIFMANAGER_ADVISE_FAILED	=2629,
	ERCO_USERDOC_ENUM_STYLE_FAILED			=2630,
	ERCO_USERDOC_CANNOT_CREATE_SERVERCLIENT	=2631,

	ERCO_APPSERV_UNABLE_TO_INIT_SECURITY	= 2640,
	ERCO_APPSERV_UNABLE_TO_GET_MODULENAME	= 2641,
	ERCO_APPSERV_NOT_REGISTERED				= 2642,
	ERCO_APPSERV_MMF_FAILED					= 2643,
	ERCO_APPSERV_OLE_INIT_FAILED			= 2644,
	ERCO_APPSERV_WORK_DIR_DIFF_REGISTRY		= 2645,

	ERCO_ODBCINSTALL_COPYINGFILEFAILED		= 2700,
	ERCO_ODBCINSTALL_GETFILEINFOFAILED		= 2701,


	ERCO_EXPIMP_FIELD_NOT_EXISTS			= 2750,
	ERCO_EXPIMP_FIELD_BAD_VALUE				= 2751,
	ERCO_EXPIMP_OBJECT_ALREADY_CRTD			= 2752,
	ERCO_EXPIMP_OBJECT_ALREADY_SAVED		= 2753,
	ERCO_EXPIMP_MSG_SAVING_WITH_UNSAVED_OBJS= 2754,
	ERCO_EXPIMP_MSG_ALREADY_SAVED			= 2755,
	ERCO_EXPIMP_PCKG_MUST_SET_STREAM_FIRST	= 2755,
	ERCO_EXPIMP_PCKG_ALREADY_SAVED			= 2756,
	ERCO_EXPIMP_SINK_NO_METHODS				= 2757,
	ERCO_EXPIMP_PCKG_ID_ALREADY_MAPPED		= 2758,
	ERCO_EXPIMP_PCKG_NEWID_MUST_BE_POSITIVE	= 2759,

	ERCO_NASE_TRYACCESSNOEXISTFUNC = 2980,
	ERCO_NASE_FUNCTIONFAILED	   = 2981,
	ERCO_NASE_READ_FAILED		   = 2982,
	ERCO_NASE_READ_BAD_PACKET_LEN  = 2983,
	ERCO_NASE_READ_BAD_PACKET_TYPE = 2984,
	ERCO_NASE_WRITE_FAILED		   = 2985,
	ERCO_NASE_RPC_BAD_PARAM_TYPE   = 2986,
	ERCO_NASE_RPC_NO_MEMORY		   = 2987,
	ERCO_NASE_RPC_INCOSISTENCE	   = 2988,
	ERCO_NASE_BACKUP_FAILED		   = 2989,
	ERCO_NASE_RESTORE_FAILED	   = 2990,
	ERCO_SOCKET_WSAERROR		   = 3000,
	
	ERCO_ADO_ERROR				   = 3050,
	ERCO_SLM_CREATECOMMAND_FAILED  = 3051,
	ERCO_SLM_INVALIDCURSORNAME	   = 3052,

	ERCO_CACHE_UNABLE_TO_INIT_SECURITY	= 3060,
	ERCO_CACHE_BAD_REQUEST_COOKIE		= 3061,
	ERCO_CACHE_BAD_ARCHIVE_VERSION		= 3062,
	ERCO_CACHE_INVALID_TRANS_ID			= 3063,
	ERCO_CACHE_GET_FILE_FAILED			= 3064,
	ERCO_CACHE_BAD_SINGLE_ARCHIVE_VERSION = 3065,
	ERCO_CACHE_BACKUP_WRITE_FAILED		= 3066,
	ERCO_CACHE_RESTORE_READ_FAILED		= 3067,

	ERCO_CACHEMAN_GET_FILE_FAILED	 = 3090,
	ERCO_CACHEMAN_STOREITEM_FAILED	 = 3091,
	ERCO_CACHEMAN_GETITEMINFO_FAILED = 3092,
	ERCO_CACHEMAN_COPY_TO_FAILED	 = 3093,
	ERCO_CACHEMAN_GETITEM_FAILED	 = 3094,
	ERCO_CACHEMAN_GETVARDEP_FAILED	 = 3095,

	ERCO_PAGECACHE_PREPROCESS_FAILED = 3100,
	ERCO_PAGECACHE_STREAM_FILTER	 = 3101,

	ERCO_SYSCHK_FAILED				= 5000,
	ERCO_SYSCHK_DCOM_NOT_INSTALLED  = 5001,
	ERCO_SYSCHK_DCOM_NOT_TURNED_ON	= 5002,
	ERCO_SYSCHK_DCOM_NOT_WORKING	= 5003,
	ERCO_SYSCHK_ENGINE_PART_NOT_INV = 5005,
	ERCO_SYSCHK_VBSCRIPT_CR_FAILED	= 5006,
	ERCO_SYSCHK_BAD_PROGID			= 5007,
	ERCO_SYSCHK_BAD_CLSID			= 5008,
	ERCO_SYSCHK_NEEDREBOOT			= 5009,
	ERCO_SYSCHK_COPYING_FAILED		= 5010,
	ERCO_SYSCHK_MDAC_CR_FAILED		= 5011,
	ERCO_SYSCHK_WIN98_OR_ABOVE_REQ	= 5012,
	ERCO_SYSCHK_MSINST_CR_FAILED	= 5013,
	ERCO_SYSCHK_NOT_ENOUGH_SPACE	= 5014,

	ERCO_GM_INVALID_DATA			= 5050,
	ERCO_GM_SAVE_FAILED				= 5051,

	//ERCO_ASK_FOR - system wide AskForData identifiers
	ERCO_ASK_FOR_RELATIVE_PATH		= 10100,
	ERCO_ASK_FOR_DB_LOCATION		= 10101,


};

const long IDS_ERROR_INFO_TEMPL	= 1;

const long IDPAGE_NOTAVAILABLE	= 0;

const long NOTF_COPYING_FILE	= 1;

//progress related informations
const long PROGRESS_END			= -1;
const long PROGRESS_BEGIN		= 0;
