services:
  navo-cocoon:
    build:
      context: .
      dockerfile: Dockerfile
    image: navo-cocoon:webhost-windows
    platform: windows/amd64
    environment:
      NAVO_COCOON_CONTAINER: "1"
      NAVO_COCOON_LISTENING_URL: "http://+:7901/"
    ports:
      - "7901:7901"
    isolation: process
