/////////////////////////////////////////////////////////////////////////////
// DDE.CPP		CDDE implementation
//
// This file is part of the Microsoft InstallWizard library.
// Copyright (C) 1994-1996 Microsoft Corporation. All rights reserved.
//
// See the InstallWizard User's Guide and InstallWizard Class Library Reference
// for detailed information regarding the InstallWizard product.
/////////////////////////////////////////////////////////////////////////////

// This file was generated by InstallWizard v1.65.00.04 on Dec 01 1998 at 13:33.


//////////////////////////////////////
// Includes
//////////////////////////////////////

#include "stdafx.h"		// included by all source files
#include "dde.h"		// external declarations for this file


//////////////////////////////////////
// Static Data
//////////////////////////////////////

CDDE*	CDDE::m_pConversation = NULL;


//////////////////////////////////////
// Constructors, Destructors, Inits
//////////////////////////////////////


CDDE::CDDE ()
{
	m_bInitialized = FALSE;
	m_dwInstanceID = 0;
}


CDDE::~CDDE ()
{
	if (m_bInitialized)
		Exit ();
}


HDDEDATA EXPORT FAR PASCAL DDECallback (UINT /*nType*/, 
										UINT /*nFormat*/,
					     				HCONV /*hConversation*/,
						 				HSZ /*hsz1*/, 
										HSZ /*hsz2*/,
						 				HDDEDATA /*hData*/,
						 				DWORD /*dwData1*/,
					     				DWORD /*dwData2*/)
{
	return (HDDEDATA) TRUE;
}



BOOL CDDE::Initialize ()              
{
	FARPROC		lpfnCallback;
	UINT		nResult;

	if (m_bInitialized)
		return TRUE;			

	ASSERT (m_pConversation == NULL);
	m_pConversation = this;
    
	lpfnCallback = MakeProcInstance ((FARPROC) DDECallback, AfxGetInstanceHandle ());	
	nResult = ::DdeInitialize (&m_dwInstanceID, (PFNCALLBACK) lpfnCallback, APPCLASS_STANDARD, 0L);
	if (nResult == DMLERR_NO_ERROR)
	{
		m_bInitialized = TRUE;
		return TRUE;
	}
	else
		return FALSE;	
}


BOOL CDDE::Exit ()
{
	m_pConversation = NULL;
	return ::DdeUninitialize (m_dwInstanceID);
}


//////////////////////////////////////
// Implementation
//////////////////////////////////////

DWORD CDDE::GetInstanceID ()
{
	Initialize (); 
	return m_dwInstanceID;
}

	

	
