/////////////////////////////////////////////////////////////////////////////
// DDE.H		CDDE interface
//
// This file is part of the Microsoft InstallWizard library.
// Copyright (C) 1994-1996 Microsoft Corporation. All rights reserved.
//
// See the InstallWizard User's Guide and InstallWizard Class Library Reference
// for detailed information regarding the InstallWizard product.
/////////////////////////////////////////////////////////////////////////////

// This file was generated by InstallWizard v1.65.00.04 on Dec 01 1998 at 13:33.


#ifndef _DDE_H_
#define _DDE_H_

//////////////////////////////////////
// Includes, Forwards
//////////////////////////////////////

// If you get 'HSZ' redefinition errors from the line below, it means you have
// included <afxext.h> without defining NO_VBX_SUPPORT somewhere before here.
#include "ddeml.h"		// for basic Windows DDEML API.


/////////////////////////////////////////////////////////////////////////////
// CDDE
/////////////////////////////////////////////////////////////////////////////

class CDDE
{
//////////////////////////////////////
// Constructors, Destructors, Inits
//////////////////////////////////////

public:
	CDDE ();
	~CDDE ();
	BOOL Initialize ();
	BOOL Exit ();

//////////////////////////////////////
// Get State
//////////////////////////////////////

public:
	DWORD GetInstanceID ();

//////////////////////////////////////
// Class Data Members
//////////////////////////////////////

protected:
	BOOL		m_bInitialized;
	DWORD 		m_dwInstanceID;
	HCONV		m_hConversation;

//////////////////////////////////////
// Static Data Members
//////////////////////////////////////

protected:
	static CDDE*	m_pConversation;
};


#endif	// !_DDE_H_


