/////////////////////////////////////////////////////////////////////////////
// DDECLNT.CPP		CDDEClient implementation
//
//
// This file is part of the Microsoft InstallWizard library.
// Copyright (C) 1994-1996 Microsoft Corporation. All rights reserved.
//
// See the InstallWizard User's Guide and InstallWizard Class Library Reference
// for detailed information regarding the InstallWizard product.
/////////////////////////////////////////////////////////////////////////////

// This file was generated by InstallWizard v1.65.00.04 on Dec 01 1998 at 13:33.


//////////////////////////////////////
// Includes
//////////////////////////////////////

#include "stdafx.h"
#include "ddeclnt.h"
#include <stdarg.h>		// for ANSI-style variable args; don't use varargs.h
#include "stdprtbl.h"		// external declarations for this file

//////////////////////////////////////
// Constants, Defines
//////////////////////////////////////

const HDDEDATA HDATA_INVALID = 0;

//////////////////////////////////////
// Additional Functions
//////////////////////////////////////

void GetData (CString& String, HDDEDATA hData)
{
	DWORD		dwLength;	
	if (hData == HDATA_INVALID)
		return;
	//DdeAccessData returns a LPBYTE so we need to convert
	//to UNICODE
	LPCSTR lpaszData = (LPCSTR) ::DdeAccessData (hData, &dwLength);
	LPTSTR lpwszData = AllocUnicodeFromANSI(lpaszData);
	String = lpwszData;
	FreeUnicode(lpwszData);

	::DdeUnaccessData (hData);	
}
	
class HString
{
public:
	HString (CDDE& rDDE);
	HString (CDDE& rDDE, LPCTSTR lpszText);
	HString (CDDE& rDDE, UINT nResourceID);
	~HString ();
	
	operator HSZ ();
	HString& operator= (LPCTSTR);

protected:
	BOOL Load (LPCTSTR lpszText);
		
protected:
	HSZ		m_hsz;
	CDDE&	m_rDDE;	
};


HString::HString (CDDE& rDDE): m_rDDE (rDDE)
{             
	m_hsz = 0;
}

HString::HString (CDDE& rDDE, LPCTSTR lpszText): m_rDDE (rDDE)
{
	Load (lpszText);
}

HString::HString (CDDE& rDDE, UINT nResourceID): m_rDDE (rDDE)
{
	CString		Text;
	
	Text.LoadString (nResourceID);
	Load (Text);
}

HString::~HString ()
{
}

HString::operator HSZ ()
{
	return m_hsz;
}

	
BOOL HString::Load (LPCTSTR lpszText)
{
#ifdef _UNICODE	
	// DdeCreateStringHandle seems to erroneously require non-const string
	m_hsz = ::DdeCreateStringHandle (m_rDDE.GetInstanceID (), (LPTSTR) lpszText, CP_WINUNICODE);	
	return (m_hsz != NULL);
#else
	#ifdef _WIN32
		// DdeCreateStringHandle seems to erroneously require non-const string
		m_hsz = ::DdeCreateStringHandle (m_rDDE.GetInstanceID (), (LPSTR) lpszText, CP_WINANSI);
	#else
		m_hsz = ::DdeCreateStringHandle (m_rDDE.GetInstanceID (), lpszText, CP_WINANSI);
	#endif
		return (m_hsz != NULL);
#endif
}	

//////////////////////////////////////
// Constructors, Destructors, Inits
//////////////////////////////////////

CDDEClient::CDDEClient ()
{
}

CDDEClient::~CDDEClient ()
{
}

//////////////////////////////////////
// Operations
//////////////////////////////////////
                                     
BOOL CDDEClient::Connect (LPCTSTR lpszService, LPCTSTR lpszTopic)
{
	HString		hService (*this, lpszService);
	HString		hTopic (*this, lpszTopic);

	Initialize ();	
	m_hConversation = ::DdeConnect (GetInstanceID (), hService, hTopic, NULL);
	return (m_hConversation != NULL);
}

BOOL CDDEClient::Disconnect ()
{
	return ::DdeDisconnect (m_hConversation);
}

void CDDEClient::Request (LPCTSTR lpszItem,
						  CString& rData,
		 				  UINT nDataFormat /*= CF_TEXT*/,
		 				  UINT uTimeout /*= TIMEOUT_ASYNC*/,
		 				  DWORD FAR *lpuResult /*= NULL*/)
{   
	HDDEDATA	hData;

	hData =  Transaction (NULL, 0,
						  lpszItem,
						  XTYP_REQUEST,
						  nDataFormat,
						  uTimeout,
						  lpuResult);
	UINT nError = ::DdeGetLastError (m_dwInstanceID);						  
	GetData (rData, hData);
}

    				
HDDEDATA CDDEClient::Command (LPBYTE lpData, DWORD cbData, 
		 					  UINT nDataFormat /*= CF_TEXT*/,
		 					  UINT uTimeout /*= TIMEOUT_ASYNC*/,
		 					  DWORD FAR *lpuResult /*= NULL*/)
{
	return Transaction (lpData, cbData, 
						_T(""),					// no hszItem
						XTYP_EXECUTE,
						nDataFormat,
						uTimeout,
						lpuResult);					  
}

HDDEDATA _cdecl CDDEClient::Command (LPCTSTR lpszFormatString, ...)
{
    char    	szBuffer [512];
    va_list 	vaArgs;
    int			nCharCount;
    
	char*	lpaszFormatString = AllocANSIFromUnicode(lpszFormatString);
    va_start (vaArgs, lpszFormatString);
    nCharCount = vsprintf (szBuffer, lpaszFormatString, vaArgs);
    va_end (vaArgs);
	FreeANSI(lpaszFormatString);
	return Command ((LPBYTE) szBuffer, nCharCount + 1, CF_TEXT);    
}
	
//////////////////////////////////////
// Implementation
//////////////////////////////////////
	
HDDEDATA CDDEClient::Transaction (LPBYTE lpData, DWORD cbData, 
						  		  LPCTSTR lpszItem,
						  		  int nTransactionType,
						  		  UINT nDataFormat /*= CF_TEXT*/,
						  		  UINT uTimeout /*= TIMEOUT_ASYNC*/,
						  		  DWORD FAR *lpuResult /*= NULL*/)
{
	HString		hItem (*this, lpszItem);
	
	Initialize ();	
	return ::DdeClientTransaction (lpData, cbData,
								   m_hConversation,
								   hItem,
								   nDataFormat,
								   nTransactionType,
								   1000,
								   lpuResult);
}
		 					  
