/////////////////////////////////////////////////////////////////////////////
// DDECLNT.H		CDDEClient interface
//
// This file is part of the Microsoft InstallWizard library.
// Copyright (C) 1994-1996 Microsoft Corporation. All rights reserved.
//
// See the InstallWizard User's Guide and InstallWizard Class Library Reference
// for detailed information regarding the InstallWizard product.
/////////////////////////////////////////////////////////////////////////////

// This file was generated by InstallWizard v1.65.00.04 on Dec 01 1998 at 13:33.

#ifndef _DDECLNT_H_
#define _DDECLNT_H_

//////////////////////////////////////
// Includes, Forwards
//////////////////////////////////////

#include "dde.h"

class CDDEException: public CException
{
};

/////////////////////////////////////////////////////////////////////////////
// CDDEClient
/////////////////////////////////////////////////////////////////////////////
 
class CDDEClient: public CDDE
{
//////////////////////////////////////
// Constructors, Destructors, Inits
//////////////////////////////////////

public:
	CDDEClient ();
	CDDEClient (LPCTSTR lpService, LPCTSTR lpszTopic);
	~CDDEClient ();

//////////////////////////////////////
// Operations
//////////////////////////////////////

public:
	BOOL Connect (LPCTSTR lpService, LPCTSTR lpszTopic);
	BOOL Disconnect (); 
	void Request (LPCTSTR lpszItem,
				  CString& Data,
				  UINT nDataFormat = CF_TEXT,
				  UINT uTimeout = TIMEOUT_ASYNC,
				  DWORD FAR *lpuResult = NULL);
	HDDEDATA _cdecl Command (LPCTSTR lpszFormatString, ...);
	HDDEDATA Command (LPBYTE lpData, DWORD cbData, 
			 		  UINT nDataFormat = CF_TEXT,
			 		  UINT uTimeout = TIMEOUT_ASYNC,
			 		  DWORD FAR *lpuResult = NULL);

//////////////////////////////////////
// Implementation
//////////////////////////////////////

protected:			 			
	HDDEDATA Transaction (LPBYTE lpvData, DWORD cbData, 
						  LPCTSTR lpszItem,
						  int nTransactionType,
						  UINT nDataFormat = CF_TEXT,
						  UINT uTimeout = TIMEOUT_ASYNC,
						  DWORD FAR *lpuResult = NULL);					  
						  

};

#endif // _DDECLNT_H_