/////////////////////////////////////////////////////////////////////////////
// PMCLIENT.CPP		CProgramManagerClient implementation
//
// This file is part of the Microsoft InstallWizard library.
// Copyright (C) 1994-1996 Microsoft Corporation. All rights reserved.
//
// See the InstallWizard User's Guide and InstallWizard Class Library Reference
// for detailed information regarding the InstallWizard product.
/////////////////////////////////////////////////////////////////////////////

// This file was generated by InstallWizard v1.65.00.04 on Dec 01 1998 at 13:33.


//////////////////////////////////////
// Includes
//////////////////////////////////////

#include "stdafx.h"		// included by all compilands
#include "pmclnt.h"		// external declarations for this file
#include "stdprtbl.h"		// external declarations for this file


//////////////////////////////////////
// Constants, Defines
//////////////////////////////////////

LPCTSTR  const szCreateGroup = _T("[CreateGroup (\"%s\")]");
LPCTSTR  const szCreateGroupFile = _T("[CreateGroup (\"%s\", \"%s\")]");
LPCTSTR  const szDeleteGroup = _T("[DeleteGroup(\"%s\")]");
LPCTSTR  const szAddItem = _T("[AddItem (%s,\"%s\",%s,%d,%d,%d,%s,%s,%d)]");
LPCTSTR  const szReplaceItem = _T("[ReplaceItem (%s)]");
LPCTSTR  const szDeleteItem = _T("[DeleteItem (%s)]");
LPCTSTR  const szProgramManagerTopic = _T("PROGMAN");
LPCTSTR  const szProgramManagerGroupItem = _T("Progman");	// not Group, like the doc says
LPCTSTR  const szProgman = _T("progman.exe");


//////////////////////////////////////
// Helper Functions
//////////////////////////////////////

inline void SurroundWithQuotes (CString& rString)
/*
	Effect:		Set rString to be the contents of rString within quotes.
				Obviously, this could have been done without a separate 
				function, but it makes the calling code easier to read.
*/
{
	rString = "\"" + rString + "\"";
}

//////////////////////////////////////
// Constructors, Destructors, Inits
//////////////////////////////////////

CProgramManagerClient::CProgramManagerClient ()
{
	m_bConnected = FALSE;
}


CProgramManagerClient::~CProgramManagerClient ()
{
	if (m_bConnected)
		Disconnect ();
}


//////////////////////////////////////
// Operations
//////////////////////////////////////

BOOL CProgramManagerClient::CreateGroup (LPCTSTR lpszGroupName, LPCTSTR lpszGroupFile /*= NULL*/)
{
	DWORD			dwReturn;

	Connect ();	
	if (lpszGroupFile != NULL)
		dwReturn = (DWORD) Command (szCreateGroupFile, lpszGroupName, lpszGroupFile);
	else
		dwReturn = (DWORD) Command (szCreateGroup, lpszGroupName);	
		
	return (dwReturn != FALSE);	
}	
	

BOOL CProgramManagerClient::DeleteGroup (LPCTSTR lpszGroupName)
{
	DWORD			dwReturn;

	Connect ();	
	dwReturn = (DWORD) Command (szDeleteGroup, lpszGroupName);
	return (dwReturn != FALSE);	
}	


BOOL CProgramManagerClient::ReplaceItem (LPCTSTR lpszDescription)
{
	DWORD		dwReturn;
	dwReturn = (DWORD) Command (szReplaceItem, lpszDescription);
	return (dwReturn != FALSE);	
}


BOOL CProgramManagerClient::DeleteItem (LPCTSTR lpszDescription)
{
	DWORD		dwReturn;
	dwReturn = (DWORD) Command (szDeleteItem, lpszDescription);
	return (dwReturn != FALSE);	
}


BOOL CProgramManagerClient::AddItem (LPCTSTR lpszCommandLine, 
										   LPCTSTR lpszDescription,
										   LPCTSTR lpszIconPath /*= NULL*/,
										   UINT nIcon /*= 0*/,
										   int xPos /*= -1*/,
										   int yPos /*= -1*/,
										   LPCTSTR lpszDefaultDirectory /*= NULL*/,
										   int nHotKey /*= -1*/,
										   BOOL bMinimize /*= 0*/)
{
	_TCHAR	szHotKey [10];
	DWORD	dwReturn;

	ASSERT (lpszCommandLine);
	ASSERT (lpszDescription);
	
	if (nHotKey == -1)
		szHotKey[0] = '\0';
	else
		_itoa (nHotKey, szHotKey, 10);
	
	Connect ();
	dwReturn = (DWORD) Command (szAddItem, lpszCommandLine,
								lpszDescription, 
								(lpszIconPath == NULL) ? lpszCommandLine : lpszIconPath,
								nIcon, xPos, yPos, 
								(lpszDefaultDirectory == NULL) ? _T("") : lpszDefaultDirectory,
								szHotKey,
								(bMinimize == 0) ? 0 : 1);
	return (dwReturn != FALSE);	
}

										   
BOOL CProgramManagerClient::FillListBox (CListBox* pListBox)
{
	CString		Groups;
	LPTSTR		lpszGroups;
	LPCTSTR		lpszGroup;

	ASSERT (pListBox);
				
	Connect ();                         
	Request (szProgramManagerGroupItem, Groups);
	lpszGroups = strdup (Groups);
	lpszGroup = strtok (lpszGroups, _T("\r\n"));
	
	while (lpszGroup)
	{
		pListBox->AddString (lpszGroup);		
		lpszGroup = strtok (NULL, _T("\r\n"));
	}

	free (lpszGroups);						
	return TRUE;
}


BOOL CProgramManagerClient::Connect (BOOL bStartIfNeeded /*= TRUE*/)
/*
	Effect:		Start a DDE Client with the program manager. If progman
				is not running, and bStartIfNeeded is nonnull, attempt to
				launch it.
*/				
{
	if (m_bConnected)
		return TRUE;
		
	if (CDDEClient::Connect (szProgramManagerTopic, szProgramManagerTopic))
	{
		m_bConnected = TRUE;
		return TRUE;
	}
	else if (bStartIfNeeded)
	{
		LPSTR aszProgman = AllocANSIFromUnicode(szProgman);
		WinExec (aszProgman, SW_SHOW);
		FreeANSI(aszProgman);

		return Connect (FALSE);
	}
	else
		return FALSE;
}

BOOL CProgramManagerClient::Disconnect ()
{
	BOOL		bSuccess;
	
	if (!m_bConnected)
		return TRUE;
		
	bSuccess = CDDEClient::Disconnect ();
	if (bSuccess)
		m_bConnected = FALSE;
		
	return bSuccess;	
}
		
/////////////////////////////////////////////////////////////////////////////
// High level methods
/////////////////////////////////////////////////////////////////////////////

// virtual 
BOOL CProgramManagerClient::CreateProgramItem (LPCTSTR lpszGroupName,
											   LPCTSTR lpszProgramPath,
											   LPCTSTR lpszArguments,
											   LPCTSTR lpszCaption,
											   LPCTSTR lpszIconPath /*= NULL*/,
											   UINT nIcon /*= 0*/,
											   int nHotKey /*= -1*/,
											   int nCmdShow /*= SW_SHOW*/)
{
	Connect ();
	CreateGroup (lpszGroupName);
	ReplaceItem (lpszCaption);

	CString	CommandLine = lpszProgramPath;
	if (CommandLine.FindOneOf (_T(" \t")) != -1)
		SurroundWithQuotes (CommandLine);

	if (lpszArguments != NULL)
	{
		CommandLine += _T(" ");
		CommandLine += lpszArguments;
	}

	BOOL	bMinimized = (nCmdShow == SW_MINIMIZE) ||
						 (nCmdShow == SW_SHOWMINIMIZED);

	return AddItem (CommandLine,
					lpszCaption,
					lpszIconPath,
					nIcon,
					nHotKey,
					bMinimized);
}


// virtual 
BOOL CProgramManagerClient::RemoveProgramItem (LPCTSTR lpszGroupName,
						LPCTSTR lpszCaption)
{
	Connect();
	CreateGroup(lpszGroupName);	 // really
	return DeleteItem (lpszCaption);
}


// virtual 
BOOL CProgramManagerClient::RemoveProgramGroup (LPCTSTR lpszGroupName,
						 BOOL bRemoveIfNotEmpty /*= FALSE*/)
{
	return DeleteGroup (lpszGroupName);
}
