/////////////////////////////////////////////////////////////////////////////
// PMCLNT.H		CProgramManagerClient interface
//
// This file is part of the Microsoft InstallWizard library.
// Copyright (C) 1994-1996 Microsoft Corporation. All rights reserved.
//
// See the InstallWizard User's Guide and InstallWizard Class Library Reference
// for detailed information regarding the InstallWizard product.
/////////////////////////////////////////////////////////////////////////////

// This file was generated by InstallWizard v1.65.00.04 on Dec 01 1998 at 13:33.



#ifndef _PMCLNT_H_
#define _PMCLNT_H_


//////////////////////////////////////
// Includes
//////////////////////////////////////

#include "ddeclnt.h"	// for parent class CDDEClient


/////////////////////////////////////////////////////////////////////////////
// CProgramManagerClient interface
/////////////////////////////////////////////////////////////////////////////


class CProgramManagerClient: public CDDEClient
{
//////////////////////////////////////
// Constructors, Destructors, Inits
//////////////////////////////////////

public:
	CProgramManagerClient ();
	~CProgramManagerClient ();

//////////////////////////////////////
// High Level Methods
//////////////////////////////////////
public:	
	virtual BOOL CreateProgramItem (LPCTSTR lpszGroupName,
									LPCTSTR lpszProgramPath,
									LPCTSTR lpszArguments,
									LPCTSTR lpszCaption,
									LPCTSTR lpszIconPath = NULL,
									UINT nIcon = 0,
									int nHotKey = -1,
									int nCmdShow = SW_SHOW);
	virtual BOOL RemoveProgramItem (LPCTSTR lpszGroupName,
									LPCTSTR lpszCaption);
	virtual BOOL RemoveProgramGroup (LPCTSTR lpszGroupName,
									 BOOL bRemoveIfNotEmpty = FALSE);
//	virtual BOOL GetFirstProgramGroup (CString& GroupName);
//	virtual BOOL GetNextProgramGroup (CString& GroupName);
	virtual BOOL FillListBox (CListBox* pListBox);

//////////////////////////////////////
// Program Manger DDE Operations
//////////////////////////////////////

public:

	BOOL Connect (BOOL bStartIfNeeded = TRUE);
	BOOL Disconnect ();
	BOOL CreateGroup (LPCTSTR lpszGroupName, LPCTSTR lpszGroupFile = NULL);
	BOOL DeleteGroup (LPCTSTR lpszGroupName);
	BOOL AddItem (LPCTSTR lpszCommandLine, 
				  LPCTSTR lpszDescription,
				  LPCTSTR lpszIconPath = NULL,
				  UINT nIcon = 0,
				  int xPos = -1,
				  int yPos = -1,
				  LPCTSTR lpszDefaultDirectory = NULL,
				  int nHotKey = -1,
				  BOOL bMinimize = 0);
	BOOL ReplaceItem (LPCTSTR lpszDescription);
	BOOL DeleteItem (LPCTSTR lpszDescription);
	BOOL GetFirstGroup (CString& GroupName);
	BOOL GetNextGroup (CString& GroupName);

//////////////////////////////////////
// Implementation
//////////////////////////////////////

protected:
	BOOL Connect1 ();
		
//////////////////////////////////////
// Object data
//////////////////////////////////////

protected:
	BOOL		m_bConnected;
};


#endif	// ! _PMCLNT_H_

