/////////////////////////////////////////////////////////////////////////////
// SHLLCLNT.H		CShellClient interface
//
// This file is part of the Microsoft InstallWizard library.
// Copyright (C) 1994-1996 Microsoft Corporation. All rights reserved.
//
// See the InstallWizard User's Guide and InstallWizard Class Library Reference
// for detailed information regarding the InstallWizard product.
/////////////////////////////////////////////////////////////////////////////

// This file was generated by InstallWizard v1.65.00.04 on Dec 01 1998 at 13:33.

#ifndef _SHLLCLNT_H_
#define _SHLLCLNT_H_

//////////////////////////////////////
// Includes, Forwards
//////////////////////////////////////

/////////////////////////////////////////////////////////////////////////////
// CShellClient interface
/////////////////////////////////////////////////////////////////////////////

class CShellClient
{
//////////////////////////////////////
// Constructors, destructors, inits
//////////////////////////////////////

public:
	CShellClient();
	~CShellClient();

//////////////////////////////////////
// High Level Methods
//////////////////////////////////////

public:
	virtual BOOL CreateProgramItem (LPCTSTR lpszGroupName,
									LPCTSTR lpszProgramPath,
									LPCTSTR lpszArguments,
									LPCTSTR lpszCaption,
									LPCTSTR lpszIconPath = NULL,
									UINT nIcon = 0,
  								    LPCTSTR lpszWorkingDirectory = NULL,
									int nHotKey = -1,
									int nCmdShow = SW_SHOW);
	virtual BOOL RemoveProgramItem (LPCTSTR lpszGroupName,
									LPCTSTR lpszCaption);
	virtual BOOL RemoveProgramGroup (LPCTSTR lpszGroupName,
									 BOOL bRemoveIfNotEmpty = FALSE);
#if (FALSE)
	// still to come
	virtual BOOL GetFirstProgramGroup (CString& GroupName);
	virtual BOOL GetNextProgramGroup (CString& GroupName);
	virtual BOOL FillListBox (CListBox* pListBox);
#endif


public:
	BOOL UseShellInterface () const { return m_bUseShellInterface; }

	BOOL Connect (BOOL bStartIfNeeded = TRUE);
	BOOL Disconnect ();
	BOOL CreateGroup (LPCTSTR lpszGroupName, LPCTSTR lpszGroupFile = NULL);
	BOOL DeleteGroup (LPCTSTR lpszGroupName, BOOL bRemoveIfNotEmpty);
	BOOL AddItem (LPCTSTR lpszCommandLine, 
				  LPCTSTR lpszDescription,
				  LPCTSTR lpszIconPath = NULL,
				  UINT nIcon = 0,
				  int xPos = -1,
				  int yPos = -1,
				  LPCTSTR lpszDefaultDirectory = NULL,
				  int nHotKey = -1,
				  BOOL bMinimize = 0);
	BOOL ReplaceItem (LPCTSTR lpszDescription);
	BOOL DeleteItem (LPCTSTR lpszGroup, LPCTSTR lpszDescription);
	BOOL GetFirstGroup (CString& GroupName);
	BOOL GetNextGroup (CString& GroupName);

//////////////////////////////////////
// Constructing Shortcut Paths
//////////////////////////////////////

protected:
	void SetShortcutProgramsPath (CPath& rPath, BOOL bCommonShortcut) const;
	void SetShortcutGroupPath (CPath& rPath,
							   LPCTSTR lpszGroupName,
							   BOOL bCommonShortcut) const;
	void SetShortcutPath (CPath& rPath,
						  LPCTSTR lpszGroupName,
						  LPCTSTR lpszCaption,
						  BOOL bCommonShortcut) const;

//////////////////////////////////////
// Object Data
//////////////////////////////////////

	static CString _get_desktop_shelllink_path();
protected:
	BOOL	m_bUseShellInterface;
	IShellLink*		m_pShellLink;
	IPersistFile*	m_pPersistFile;
	CPath			m_CommonProgramsShortcutPath;
	CPath			m_UserProgramsShortcutPath;
	CPath			m_CommonStartupShortcutPath;
};


#endif	// !_SHLLCLNT_H_

