/////////////////////////////////////////////////////////////////////////////
// SHLLCLNT.CPP		CShellClient implementation
//
// This file is part of the Microsoft InstallWizard library.
// Copyright (C) 1994-1996 Microsoft Corporation. All rights reserved.
//
// See the InstallWizard User's Guide and InstallWizard Class Library Reference
// for detailed information regarding the InstallWizard product.
/////////////////////////////////////////////////////////////////////////////

// This file was generated by InstallWizard v1.65.00.04 on Dec 01 1998 at 13:33.


//////////////////////////////////////
// Includes, Forwards
//////////////////////////////////////

#include "stdafx.h"		// included by all compilands
#include "..\include\h1000.h"
#include "path.h"		// for CPath; shell links are shortcut files
#include "shllclnt.h"	// external declarations for this file
//#include "..\iwlib32\environ.h"	// for CEnvironment::SupportsShell
#include <objbase.h>	// for OLE base
#include <winnetwk.h>
#include <winnls.h>		// for MultiByteToWideChar
#include "..\navocomutil\specialfolders.h"

//////////////////////////////////////
// Constants, Defines
//////////////////////////////////////


LPCTSTR const szShortcutExtension = _T("lnk");

LPCTSTR	const szUserProgramsPathRegistryKey = _T("Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Shell Folders");
LPCTSTR const szUserProgramsPathValueName = _T("Programs");
LPCTSTR	const szUserProgramsDefaultDirectory = _T("\\Start Menu\\Programs");

LPCTSTR const szCommonProgramsPathRegistryKey = _T("Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Shell Folders");
LPCTSTR const szCommonProgramsPathValueName = _T("Common Programs");
LPCTSTR	const szCommonProgramsDefaultDirectory = _T("\\Start Menu\\Programs");

LPCTSTR const szCommonStartupPathValueName = _T("Common Startup");
LPCTSTR const szStartupPathValueName = _T("Startup");
LPCTSTR	const szCommonStartupDefaultDirectory = _T("\\Start Menu\\Startup");


//////////////////////////////////////
// Constructors, Destructors, Inits
//////////////////////////////////////

CShellClient::CShellClient ()
/*
	Effect		Initialize this CShellClient object and it's data members.
				Establish whether the object should communicate with the
				system via the shell interface or use the older DDE method.
*/
{
	m_pShellLink = NULL;
	m_pPersistFile = NULL;

	//////////////////////////////////////
	// Use shell interface?
	//////////////////////////////////////

#ifdef _WIN32
	//////////////////////////////////////
	// Determine Shortcut Paths
	//////////////////////////////////////

	//// Determine current user programs path 

	CString RegisteredUserShortcutPath;
	SafeGetRegistryKeyString(HKEY_CURRENT_USER, szUserProgramsPathRegistryKey, szUserProgramsPathValueName, RegisteredUserShortcutPath);
//	CRegistryString	RegisteredUserShortcutPath (HKEY_CURRENT_USER,
//												szUserProgramsPathRegistryKey,
//												szUserProgramsPathValueName);
	m_UserProgramsShortcutPath.SetDriveDirectory (RegisteredUserShortcutPath);
	if (m_UserProgramsShortcutPath.IsEmpty())
	{
		m_UserProgramsShortcutPath.WindowsDirectory();
		m_UserProgramsShortcutPath.AppendDirectory (szUserProgramsDefaultDirectory);
	}

	//// Determine common programs path

	OSVERSIONINFO ovi;
	ovi.dwOSVersionInfoSize = sizeof(OSVERSIONINFO);
	VERIFY(::GetVersionEx(&ovi));
	if (ovi.dwPlatformId == VER_PLATFORM_WIN32_NT)
	{
		CString RegisteredCommonShortcutPath;
		SafeGetRegistryKeyString(HKEY_LOCAL_MACHINE, szCommonProgramsPathRegistryKey, szCommonProgramsPathValueName, RegisteredCommonShortcutPath);
//		CRegistryString	RegisteredCommonShortcutPath (HKEY_LOCAL_MACHINE,
//													  szCommonProgramsPathRegistryKey,
//													  szCommonProgramsPathValueName);
		m_CommonProgramsShortcutPath.SetDriveDirectory (RegisteredCommonShortcutPath);
		if (m_CommonProgramsShortcutPath.IsEmpty())
		{
			m_CommonProgramsShortcutPath.WindowsDirectory();
			m_CommonProgramsShortcutPath.AppendDirectory (szCommonProgramsDefaultDirectory);
		}
	}
	else
	{
		// Windows 95 doesn't have a separate spot for common shortcuts.
		m_CommonProgramsShortcutPath = m_UserProgramsShortcutPath;
	}

	CString RegisteredCommonStartupPath;
	if (SafeGetRegistryKeyString(HKEY_LOCAL_MACHINE, szCommonProgramsPathRegistryKey, szCommonStartupPathValueName, RegisteredCommonStartupPath) != ERROR_SUCCESS)
	{
		SafeGetRegistryKeyString(HKEY_CURRENT_USER, szCommonProgramsPathRegistryKey, szStartupPathValueName, RegisteredCommonStartupPath);
	};
	m_CommonStartupShortcutPath.SetDriveDirectory (RegisteredCommonStartupPath);
	if (m_CommonStartupShortcutPath.IsEmpty())
	{
		m_CommonStartupShortcutPath.WindowsDirectory();
		m_CommonStartupShortcutPath.AppendDirectory (szCommonStartupDefaultDirectory);
	}
#endif	// _WIN32
}


CShellClient::~CShellClient()
{
	if (m_pShellLink != NULL)
		Disconnect();
}



BOOL CShellClient::Connect (BOOL bStartIfNeeded)
{
	HRESULT			hResult;

	hResult = CoInitialize (NULL);
	hResult = CoCreateInstance (CLSID_ShellLink,	// class identifier
								NULL,				// not an aggregate
								CLSCTX_INPROC_SERVER,
								IID_IShellLink,
								(void**)&m_pShellLink);
	if (SUCCEEDED (hResult))
		hResult = m_pShellLink->QueryInterface(IID_IPersistFile, 
						(void **)&m_pPersistFile);

	return (SUCCEEDED (hResult));
}

BOOL CShellClient::Disconnect ()
{
	if (m_pPersistFile != NULL)
	{
		m_pPersistFile->Release();
		m_pPersistFile = NULL;
	}
	if (m_pShellLink != NULL)
	{
		m_pShellLink->Release();
		m_pShellLink = NULL;
	}
	return TRUE;
}


BOOL CShellClient::CreateGroup (LPCTSTR lpszGroupName, 
								LPCTSTR lpszGroupFile /*= NULL*/)
{
	CPath		ShortcutPath;

	SetShortcutGroupPath (ShortcutPath, lpszGroupName, TRUE);
	return ShortcutPath.CreateDirectory();
}

BOOL CShellClient::DeleteGroup (LPCTSTR lpszGroupName, BOOL bRemoveIfNotEmpty)
{
	CPath		ShortcutPath;
	SetShortcutGroupPath (ShortcutPath, lpszGroupName, TRUE);
	if (bRemoveIfNotEmpty)
	{
		return NavoRemoveDirectoryTree(CString((LPCTSTR)ShortcutPath));
	}
	else
	{
		return ShortcutPath.RemoveDirectory();
	};
}

BOOL CShellClient::ReplaceItem (LPCTSTR lpszDescription)
{
	return TRUE;
}

BOOL CShellClient::DeleteItem (LPCTSTR lpszGroup, LPCTSTR lpszDescription)
{
	CPath	ShortcutPath;
	SetShortcutPath (ShortcutPath, lpszGroup, lpszDescription, TRUE);
	return ShortcutPath.Delete();
}


/////////////////////////////////////////////////////////////////////////////
// High level methods
/////////////////////////////////////////////////////////////////////////////

BOOL CShellClient::CreateProgramItem (LPCTSTR lpszGroupName,
											  LPCTSTR lpszProgramPath,
										 	  LPCTSTR lpszArguments,
											  LPCTSTR lpszCaption,
											  LPCTSTR lpszIconPath /*= NULL*/,
											  UINT nIcon /*= 0*/,
											  LPCTSTR lpszWorkingDirectory /*= NULL*/,
											  int nHotKey /*= -1*/,
											  int nCmdShow /*= SW_SHOW*/)
{
	CString oGroupNameString(lpszGroupName);
	bool bSpecialGroup = false;
	if (oGroupNameString.GetLength() > 2 && oGroupNameString.GetAt(0) == '@' && oGroupNameString.GetAt(oGroupNameString.GetLength() - 1) == '@')
	{
		bSpecialGroup = true;
		oGroupNameString = CString((LPCTSTR)oGroupNameString + 1, oGroupNameString.GetLength() - 2);
		if (!oGroupNameString.CompareNoCase("startup"))
		{
			oGroupNameString = (LPCTSTR)m_CommonStartupShortcutPath;
		}
		else
		if (!oGroupNameString.CompareNoCase("desktop"))
		{
			oGroupNameString = (LPCTSTR)_get_desktop_shelllink_path();
		}
		else
		{
			ASSERT(false);
		};
	};

	Connect ();

	CPath		ShortcutGroupPath;
	CPath		ShortcutPath;
	if (bSpecialGroup)
	{
		ShortcutGroupPath = oGroupNameString;
		ShortcutPath.SetDriveDirectory(oGroupNameString);
		ShortcutPath.SetName(CString(lpszCaption) + '.' + szShortcutExtension);
	}
	else
	{
		SetShortcutGroupPath (ShortcutGroupPath, oGroupNameString, TRUE);
		SetShortcutPath (ShortcutPath,
						 oGroupNameString, 
						 lpszCaption, 
						 TRUE);
	}
	ShortcutGroupPath.CreateDirectory ();

	CString oWorkingDirectoryStr;
	if (lpszWorkingDirectory)
	{
		oWorkingDirectoryStr = lpszWorkingDirectory;
	}
	else
	{
		CString oProgramPathStr(lpszProgramPath);
		long lNameIndex = oProgramPathStr.ReverseFind('\\');
		if (lNameIndex == -1)
		{
			lNameIndex = oProgramPathStr.ReverseFind('/');
		};
		if (lNameIndex != -1)
		{
			oWorkingDirectoryStr = CString(lpszProgramPath, lNameIndex);
		};
	};

	m_pShellLink->SetPath (lpszProgramPath);
	m_pShellLink->SetArguments (lpszArguments);
	m_pShellLink->SetDescription (lpszCaption);
	m_pShellLink->SetWorkingDirectory(oWorkingDirectoryStr);

#ifndef _UNICODE
	int nLen = MultiByteToWideChar(CP_ACP,	
						0, 
						ShortcutPath, 
						strlen(ShortcutPath), 
						NULL, 
						0);
	LPWSTR wszShortcutPath = new WCHAR[nLen+1];
	
	MultiByteToWideChar(CP_ACP,	
						0, 
						ShortcutPath, 
						strlen(ShortcutPath), 
						wszShortcutPath, 
						nLen);

	wszShortcutPath[nLen] = '\0';	//assure null termination

	HRESULT hResult = m_pPersistFile->Save (wszShortcutPath, TRUE);
	delete[] wszShortcutPath;
#else
	HRESULT hResult = m_pPersistFile->Save (ShortcutPath, TRUE);
#endif
	Disconnect();
	return (SUCCEEDED (hResult));
}


// virtual 
BOOL CShellClient::RemoveProgramItem (LPCTSTR lpszGroupName,
									 LPCTSTR lpszCaption)
{
	CString oGroupNameString(lpszGroupName);
	bool bSpecialGroup = false;
	if (oGroupNameString.GetLength() > 2 && oGroupNameString.GetAt(0) == '@' && oGroupNameString.GetAt(oGroupNameString.GetLength() - 1) == '@')
	{
		bSpecialGroup = true;
		oGroupNameString = CString((LPCTSTR)oGroupNameString + 1, oGroupNameString.GetLength() - 2);
		if (!oGroupNameString.CompareNoCase("startup"))
		{
			oGroupNameString = (LPCTSTR)m_CommonStartupShortcutPath;
		}
		else
		if (!oGroupNameString.CompareNoCase("desktop"))
		{
			oGroupNameString = (LPCTSTR)_get_desktop_shelllink_path();
		}
		else
		{
			ASSERT(false);
		};
	};
	CPath		ShortcutPath;

	if (bSpecialGroup)
	{
		ShortcutPath.SetDriveDirectory(oGroupNameString);
		ShortcutPath.SetName(CString(lpszCaption) + '.' + szShortcutExtension);
	}
	else
	{
		SetShortcutPath (ShortcutPath,
						 oGroupNameString,
						 lpszCaption,
						 TRUE);
	}
	return ShortcutPath.Delete ();
}


// virtual 
BOOL CShellClient::RemoveProgramGroup (LPCTSTR lpszGroupName,
										BOOL bRemoveIfNotEmpty /*= FALSE*/)
{
	return DeleteGroup (lpszGroupName, bRemoveIfNotEmpty);
}



//////////////////////////////////////
// Constructing Shortcut Paths
//////////////////////////////////////

// protected
void CShellClient::SetShortcutProgramsPath (CPath& rPath, 
											BOOL bCommonShortcut) const
{
	if (bCommonShortcut)
		rPath = m_CommonProgramsShortcutPath;
	else
		rPath = m_UserProgramsShortcutPath;
}


// protected
void CShellClient::SetShortcutGroupPath (CPath& rPath,
										 LPCTSTR lpszGroupName,
										 BOOL bCommonShortcut) const
{
	SetShortcutProgramsPath (rPath, bCommonShortcut);
	rPath.AppendDirectory (lpszGroupName);
}


// protected
void CShellClient::SetShortcutPath (CPath& rPath,
									LPCTSTR lpszGroupName,
									LPCTSTR lpszCaption,
								    BOOL bCommonShortcut) const
{
	SetShortcutGroupPath (rPath, lpszGroupName, bCommonShortcut);

	rPath.SetName (CString(lpszCaption) + '.' + szShortcutExtension);
//	rPath.SetExtension (szShortcutExtension);
}


CString CShellClient::_get_desktop_shelllink_path()
{
	return _get_special_folder_path(nsf_desktop);
}

