//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by setup.rc
//
#define IDC_LOCALCHOOSE                 4
#define IDC_INETCHOOSE                  5
#define IDS_WIN98_OR_ABOVE_REQUIRED     18
#define IDS_NAVOAPP_ALREADY_RUNNING     19
#define IDS_IE401SP2_OR_ABOVE_REQUIRED  20
#define IDS_OK_TO_UNINSTALL             21
#define IDS_LICENCETEXT1                22
#define IDS_LICENCETEXT2                23
#define IDS_LICENCETEXT3                24
#define IDS_LICENCETEXT4                25
#define IDS_LICENCETEXT5                26
#define IDS_LICENCETEXT6                27
#define IDS_LICENCETEXT7                28
#define IDS_LICENCETEXT8                29
#define IDS_LICENCETEXT9                30
#define IDS_LICENCETEXT10               31
#define IDS_LICENCETEXT11               32
#define IDP_OLE_INIT_FAILED             100
#define IDD_LOGIN                       101
#define IDD_SETUP_DIALOG                102
#define IDR_MAINFRAME                   128
#define IDD_WELCOMEDLG                  129
#define IDD_CHOOSEAPPDLG                130
#define IDD_INSTALLCOMPDLG              131
#define IDD_CHOOSEMODEDLG               132
#define IDD_LICENCEDLG                  133
#define IDS_RESTARTINFO                 133
#define IDD_INFODLG                     134
#define IDS_PROGRESSTITLE               134
#define IDS_PROGRESSTITLE2              135
#define IDS_PROGRESSTITLE3              136
#define IDD_CONFIRM                     136
#define IDD_CONFIRMDLG                  136
#define ID_NEXT                         1000
#define IDC_USER                        1000
#define IDS_stpe_ok                     1000
#define IDC_MONITOR                     1000
#define IDC_BACK                        1001
#define IDC_PASSWORD                    1001
#define IDS_stpe_not_enough_rights      1001
#define IDC_AUTOMATIC                   1002
#define IDC_DOMAIN                      1002
#define IDS_stpe_syschk_bad_clsid       1002
#define IDC_nec_wininst                 1003
#define IDS_stpe_syschk_bad_progid      1003
#define IDC_ROOTDESTPATH                1003
#define IDC_LIST1                       1004
#define IDC_nec_mdac                    1004
#define IDS_stpe_cant_read_param        1004
#define IDC_LOCATIONTEXT                1004
#define IDC_SINGLE                      1005
#define IDC_nec_vbscript                1005
#define IDS_stpe_cant_write_param       1005
#define IDC_SERVER                      1006
#define IDS_stpe_param_corrupted        1006
#define IDC_WORKSTATION                 1007
#define IDC_nec_dcom                    1007
#define IDS_stpe_user_break             1007
#define IDC_SERVERTEXT                  1008
#define IDC_nec_engine                  1008
#define IDS_stpe_bad_cmd_line           1008
#define IDC_SERVERNAME                  1009
#define IDS_stpe_comobj_check_fail      1009
#define IDC_nec_dotnet                  1010
#define IDC_MODESTATIC                  1010
#define IDS_stpe_restart_required       1010
#define IDC_APPSTATIC                   1011
#define IDC_EDIT                        1011
#define IDS_stpe_internal_error         1011
#define IDC_BROWSE                      1011
#define IDC_PICTURE                     1012
#define IDS_stpe_appdb_create_fail      1012
#define IDC_DESTPATHSTATIC              1013
#define IDS_stpe_appdb_init_fail        1013
#define IDS_stpe_appdb_unpack_fail      1014
#define IDS_stpe_file_copy_failed       1015
#define IDC_MANUAL                      1015
#define IDS_stpe_register_failed        1016
#define IDS_stpe_openservice_failed     1017
#define IDS_stpe_startservice_failed    1018
#define IDC_UNINSTALL                   1018
#define IDS_stpe_stopservice_failed     1019
#define IDC_MESSAGE                     1019
#define IDS_stpe_getstateservice_fail   1020
#define IDS_stpe_unable_2_open_file     1021
#define IDS_stpe_download_failed        1022
#define IDS_stpe_file_size_incorrect    1023
#define IDS_stpe_appdbman_create_fail   1024
#define IDS_stpe_registry_write_fail    1025
#define IDS_stpe_finished               1026
#define IDS_stpe_bad_monitor_command    1027
#define IDC_OK                          1027
#define IDS_stpe_monitor_failed         1028
#define IDC_LOCAL                       1028
#define IDC_REMOTE                      1029
#define IDS_stpe_file_not_found         1029
#define IDC_REMOTEALL                   1030
#define IDS_not_enough_disk_spc         1030
#define IDS_DETECTING_COMPONENTS        1031
#define IDS_CREATING_DIR                1032
#define IDS_UPDATING_REGISTRY           1033
#define IDC_APPLIST                     1034
#define IDS_COPYING_FILE                1034
#define IDC_EDIT1                       1035
#define IDS_REGISTERING_FILE            1035
#define IDS_DELETING_FILE               1036
#define IDC_CHECK1                      1036
#define IDS_TESTING_APPDBMAN            1037
#define IDS_CREATING_APP                1038
#define IDS_UNPACKING_APP               1039
#define IDC_PROGRESS1                   4000
#define IDD_DIALOGPROGRESS              4000
#define IDD_BROWSEDLG                   4001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1037
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
