// navobrmctrl2008.idl : type library source for ActiveX Control project.

// This file will be processed by the MIDL compiler tool to
// produce the type library (navobrmctrl2008.tlb) that will become a resource in
// navobrmctrl2008.ocx.

#include <olectl.h>
#include <idispids.h>

[ uuid(EE4EB3CA-DB78-4860-A710-662F72C39FC5), version(1.0),
  control ]
library navobrmctrl2008Lib
{
	importlib(STDOLE_TLB);

	
	//  Primary dispatch interface for CCNAVOBRMCtrl
	[ 
		uuid(624555E0-29AA-4BDE-B0A3-5E5F1390ED28)	
	]
	dispinterface _Dnavobrmctrl2008
	{
    properties:
        [id(0x00000001)        
]
        VARIANT_BOOL compress;
        [id(0x00000003)        
]
        VARIANT datastream;
        [id(0x00000004)        
]
        VARIANT infostream;
        [id(0x00000002)        
]
        long splitsize;
        [id(0x00000005)        
]
        IDispatch* sink;
        [id(0x00000006)        
]
		BSTR description;
		[id(0x00000020)
		]
		BSTR rootdir;
    methods:
        [id(0x00000007)]
        long restore();
        [id(0x0000000c), propget]
        BSTR profile(
                        BSTR lpServerName, 
                        long nProfile);
        [id(0x0000000c), propput]
        void profile(
                        BSTR lpServerName, 
                        long nProfile, 
                        BSTR rhs);
        [id(0x00000008)]
        IDispatch* newbrset();
        [id(0x00000009)]
        long backup();
        [id(0x0000000a)]
        void addbrset(IDispatch* pBRSet);
        [id(0x0000000b)]
        long readheader();
        [id(0xfffffdd8)]
        void AboutBox();
};

	//  Event dispatch interface for CCNAVOBRMCtrl

	[ 
		uuid(69E3EFCF-A739-4879-A999-0C70E550E23A)	
	]
	dispinterface _Dnavobrmctrl2008Events
	{
		properties:
			//  Event interface has no properties

		methods:
	};

	//  Class information for CCNAVOBRMCtrl
	[
		uuid(B4222B0F-ED29-4ECC-9B57-995A5E222540)
	]
	coclass navobrmctrl2008
	{
		[default] dispinterface _Dnavobrmctrl2008;
		[default, source] dispinterface _Dnavobrmctrl2008Events;
	};

};
