#comment UWAGA: 1000-3000 - CMDID generowane do uprawnieñ
#comment 3000 - xxx : pomijane
#comment BD_VER4 = upraweniia wrzucac do odpowiedniego pliku wczytywanego przy upgradzi'e


#comment WOLNE!!!

#define CMDID_ZLECPROD							1020
#define CMDID_REALPROD							1021
#define CMDID_REJESTRUJ_KONTAKT					1022
#define CMDID_MAKE_NOTE							1023
#define CMDID_KORESPONDENCJA					1024
#define CMDID_NAPISZ_WIADOMOSC					1025
#define CMDID_ZLEC_ZADANIE						1026
#define CMDID_LOGON								1027
#define CMDID_ROZLICZENIE_VATUE					1028

#comment CMDID_QUICK_ACCES=1029 jest przypisane jako domyœlna komenda startowa (USERPROF_STARTING_CMDID)

#define CMDID_QUICK_ACCES						1029

#define CMDID_CLIENT_LOGON						1030
#define CMDID_CHANGE_RKS						1031
#define CMDID_ROZLICZENIE_VAT					1032
#define CMDID_ROZLICZENIE_CIT					1033
#define CMDID_CHOROBA							1034
#define CMDID_NIEOBECNOSCI						1035
#define CMDID_NALICZENIE						1036
#define CMDID_SEARCH_CUSTOMER					1037
#define CMDID_SEARCH_DOCUMENT					1038
#define CMDID_SEARCH_TASK						1039
#define CMDID_SEARCH_PRODUCT					1040
#define CMDID_SEARCH_KONTO						1041
#define CMDID_SEARCH_DEKRET						1042
#define CMDID_SEARCH_BWINFO						1043
#define CMDID_EXPLORER_CUSTOMERS				1044
#define CMDID_EXPLORER_PRODUCTS					1045
#define CMDID_EXPLORER_DOCUMENTS				1046
#define CMDID_EXPLORER_TASKS					1047
#define CMDID_EXPLORER_TASKS_BY_CUSTOMERS		1048
#define CMDID_DEFINE_EXPORT_FILTER				1049
#define CMDID_EXPLORER_FIRM						1050
#define CMDID_KLIENT_FIRMA						1051
#define CMDID_KLIENT_OSOBA_PRYWATNA				1052
#define CMDID_PRAC_KLIENT						1053
#define CMDID_KLIENT_JO							1054
#define CMDID_PRODUKT							1055
#define CMDID_CENY_RABATY						1056
#define CMDID_TRANSAKCJE						1057
#define CMDID_KURSY_WALUT						1058
#define CMDID_RECEPTA							1059
#define CMDID_ZADANIA_ZLECONE					1060
#define CMDID_ZADANIA_ODEBRANE					1061
#define CMDID_ZADANIA_REALIZOWANE				1062
#define CMDID_ZADANIA_WSTRZYMANE				1063
#define CMDID_ZADANIA_ZAKONCZONE				1064
#define CMDID_ZADANIA_ZAMKNIETE				1065
#define CMDID_BANK							1066
#define CMDID_URZAD							1067
#define CMDID_KONTO							1068
#define CMDID_SRT							1069
#define CMDID_BWKATINFO						1070
#define CMDID_BWINFO						1071
#define CMDID_RAPORT_PLACE_ZBIORCZA			1072
#define CMDID_UMOWA							1073
#define CMDID_WIZZARD_EMAIL						1074
#define CMDID_WIZZARD_IMPORT_CON					1075
#define CMDID_WIZZARD_WIZYTOWKA					1076
#define CMDID_WIZZARD_OFERTA						1077
#define CMDID_WIZZARD_ETYKIETY						1078
#define CMDID_WIZZARD_PRZYDZIAL_ZADAN				1079
#define CMDID_WIZZARD_FAKTURY_ABONAMENTOWE			1080
#define CMDID_WIZZARD_PUBLIKACJE					1081
#define CMDID_CHAT									1082
#define CMDID_SEGREGOWANIE_POCZTY					1083
#define CMDID_WIZZARD_RULES						1084
#define CMDID_WIZZARD_IMPEXP38						1085
#define CMDID_WIZZARD_IMPEXPEUROBIZNES				1086
#define CMDID_WIZZARD_IMPEXPXLS					1087
#define CMDID_WIZZARD_IMPEXPEXT					1088
#define CMDID_WEBSERVICES							1089
#define CMDID_WIZZARD_EXPXML						1090
#define CMDID_CHOICELIST							1091
#define CMDID_OPEN_PAGE_EXT						1092
#define CMDID_OPEN_PAGE_NET						1093
#define CMDID_RAPORT_FORMA_DZISIAJ					1094
#define CMDID_RAPORT_ZADANIA_WYKRES_PROCENTY		1095	
#define CMDID_RAPORT_VAT_PODSUMOWANIE				1096
#define CMDID_RAPORT_VAT_STAWKAMI					1097
#define CMDID_RAPORT_VAT_WPISY						1098																							
#define CMDID_RAPORT_MAGAZYN_ZMIENNOSC				1099
#define CMDID_RAPORT_MAGAZYN_STANY					1100	
#define CMDID_RAPORT_MAGAZYN_WARTOSC				1101
#define CMDID_RAPORT_MAGAZYN_PODSUMOWANIE			1102
#define CMDID_RAPORT_MAGAZYN_SZCZEG				1103
#define CMDID_RAPORT_ZADANIA_DO_WYKONANIA			1104
#define CMDID_RAPORT_ZADANIA_PRZETERMINOWANE		1105
#define CMDID_RAPORT_ZADANIA_DO_WYKONIANIA_PRZEZ	1106
#define CMDID_RAPORT_ZADANIA_PRZETERMINOWANE_DLA	1107
#define CMDID_RAPORT_ZADANIA_BIEZACE_KLIENT		1108
#define CMDID_RAPORT_KLIENCI_OBROTY				1109
#define CMDID_RAPORT_TRANS_PRZETERMINOWANE			1110
#define CMDID_RAPORT_TRANS_NIEROZLICZONE			1111
#define CMDID_RAPORT_ZOB_PRZETERMINOWANE			1112
#define CMDID_RAPORT_ZOB_NIEROZLICZONE				1113
#define CMDID_RAPORT_TRANS_WSZYSTKIE				1114
#define CMDID_OPTIONPAD_RAPORT_MAGAZYN				1115
#define CMDID_OPTION_PAD_RAPORT_PLACE				1116
#define CMDID_RAPORT_PLACE_INDYWIDUALNA				1117
#define CMDID_OPTIONPAD_DZIALANIA					1118
#define CMDID_RAPORT_OPER_FINANS					1119
#define CMDID_RAPORT_KALENDARZ_DZIS					1120
#define CMDID_RAPORT_KALENDARZ_TYDZIEN				1121
#define CMDID_RAPORT_KALENDARZ_MIESIAC				1122
#define CMDID_RAPORT_ZDARZENIA_SYS					1123
#define CMDID_RAPORT_USER							1124
#define CMDID_RAPORT_DZIENNIK_SKROT				1125
#define CMDID_RAPORT_DZIENNIK_SZCZEGOLY			1126
#define CMDID_RAPORT_DZIENNIK_DOWODY				1127
#define CMDID_RAPORT_ZAPISY_NA_KONTACH				1128
#define CMDID_RAPORT_OBROTY_SALDA					1129
#define CMDID_RAPORT_OBROTY_SALDA_DZIEN			1130
#define CMDID_DANE_FIRMY							1131
#define CMDID_PAD_NASZA_FIRMA						1132
#define CMDID_PRACOWNIK							1133
#define CMDID_WYKONAWCA							1134
#define CMDID_UZYTKOWNIK							1135
#define CMDID_JO									1136
#define CMDID_UZYTKOWNIK_SZABLON					1137
#define CMDID_REJESTROWANIE_ZDARZEN_SYS			1138
#define CMDID_PAD_GRUPY_KATEGORIE					1139
#define CMDID_MIARA								1140
#define CMDID_WALUTA								1141
#define CMDID_SPOSOB_PLATNOSCI						1142
#define CMDID_MAGAZYN								1143
#define CMDID_REJESTR								1144
#define CMDID_GRUPAKLIENTOW						1145
#define CMDID_GRUPAPROD							1146
#define CMDID_BRANZA								1147
#define CMDID_TYPDOK								1148
#define CMDID_TYPINST								1149
#define CMDID_TYPDZIALANIA							1150
#define CMDID_MIEJSCOWOSC							1151
#define CMDID_WOJEWODZTWO							1152
#define CMDID_REGION								1153
#define CMDID_KRAJ									1154
#define CMDID_PODZIAL_TERYTORIALNY					1155
#define CMDID_MOJE_DANE							1156
#define CMDID_MOJE_PREFERENCJE						1157
#define CMDID_SETUP_OUTLOOKBAR						1158
#define CMDID_POLITYKA_FIRMY						1159
#define CMDID_ZMIEN_PARAMETRY						1160
#define CMDID_FILTRY								1161
#define CMDID_RAPORTY								1162
#define CMDID_USTAWIENIA_KOMPUTERA					1163
#define CMDID_ROK_KSIEGOWY							1164
#define CMDID_BUDZET								1165
#define CMDID_KWALIFIKATOR							1166
#define CMDID_SCHEM_DEKR							1167
#define CMDID_ABOUT									1168
#define CMDID_NAPRAWA_BAZY							1169
#define CMDID_DZIENNIK_DK							1170
#define CMDID_GRUPA_SRT								1171
#define CMDID_STAWKA_NALICZEN						1172
#define CMDID_RAPORT_ZADANIA_AKTYWNOSC				1173
#define CMDID_OPTIONPAD_PROLOJ						1174
#define CMDID_KONTO_PRACOWNICZE						1175
#define CMDID_SCHEMAT_NALICZEN						1176
#define CMDID_RAPORT_ZADANIA_WYKRES_ILOSC			1177
#define CMDID_RAPORT_PROD_OFERTA					1178	
#define CMDID_RAPORT_PROD_CENNIK					1179
#define CMDID_RAPORT_PROD_CZESTOTLIWOSC				1180
#define CMDID_RAPORT_PROD_ILOSC						1190
#define CMDID_RAPORT_PROD_OBROTY					1191
#define CMDID_EXT_INET								1192
#define CMDID_WYSLIJ_EMAIL							1193
#define CMDID_TRANSAKCJA							1194
#define CMDID_EXPLORER_KONTA						1195
#define CMDID_RAPORT_OPERACJE_MAGAZYNOWE			1196
#define CMDID_RAPORT_STRUKT_WIEKOWA_NAL				1197
#define CMDID_OPTIONPAG_DOK_MAG						1198
#define CMDID_OPTIONPAG_RAPORT_TRANSAKCJE			1199
#define CMDID_OPTIONPAD_ZAKUP_EWID					1200
#define CMDID_BROWSER_CONFIGURATION					1201
#define CMDID_DEDUPLIKATOR							1202
#define CMDID_FUZZY_SEARCH_CONFIGURATION			1203

#define CMDID_PKPIR_FORM							1204
#define CMDID_RAPORT_PKPIR_LISTA					1205
#define CMDID_RAPORT_SPRZEDAZ_VS_DOKMAG				1206
#define CMDID_RAPORT_MAG_PRZYCH_ROZCHODY			1207
#define CMDID_RAPORT_MAG_ROTACJA					1208
#define CMDID_LISTA_FAKTUR							1209
#define CMDID_LISTA_RACHUNKOW						1210
#define CMDID_LISTA_PARAGONOW						1211
#define CMDID_LISTA_ZAMOWIEN						1212
#define CMDID_LISTA_WZ								1213
#define CMDID_LISTA_PZ								1214
#define CMDID_RAPORT_ZAMOW_KLIENT					1215
#define CMDID_RAPORT_ZAMOW_PRODUKT					1216
#define CMDID_RAPORT_BUDZET_KONT					1217
#define CMDID_SPIKO_TEST							1218
#define CMDID_RAPORT_ANALFINAS_TABLE				1219
#define CMDID_FORM_ANALFINAS						1220
#define CMDID_EWID_SPRZED							1221
#define CMDID_EWID_ZAKUP							1222
#define CMDID_LISTA_PRODUKTOW						1223
#define CMDID_LISTA_USLUG							1224
#define CMDID_WIZZARD_EXPPLAT						1225
#define CMDID_OPTIONPAD_NOWE_DZIALANIA				1226
#define CMDID_WIZZARD_REAL_ZAM						1227
#define CMDID_RAPORT_WOLNOSPRZEDAJACE_SIE			1228
#define CMDID_PAKOWANIE								1229
#define CMDID_ROZPAKOWANIE							1230
#define CMDID_ZAMOWIENIE_WLASNE						1231
#define CMDID_NOTAODS								1232
#define CMDID_OPTIONPAD_OPSRTW						1233

#define CMDID_OPSRTW_ZAKUP							1234
#define CMDID_OPSRTW_PRZYJECIE_OT					1235
#define CMDID_OPSRTW_AMORTYZACJA					1236
#define CMDID_OPSRTW_PRZESZACOWANIE_PK				1237
#define CMDID_OPSRTW_ZMIANA_WARTOSCI_WK				1238
#define CMDID_OPSRTW_SPRZEDAZ						1239
#define CMDID_OPSRTW_LIKWIDACJA_LT					1240
#define CMDID_OPSRTW_PRZYJECIE_PT					1241
#define CMDID_OPSRTW_PRZEKAZANIE_PR					1242
#define CMDID_OPSRTW_ZMIANA_OSOBY					1243
#define CMDID_OPSRTW_ZMIANA_MIEJSCA					1244
#define CMDID_OPSRTW_ZMIANA_STAWKI					1245
#define CMDID_OPSRTW_KOREKTA_AMORT					1246
#define CMDID_WIZZARD_INWENTARYZACJA				1247
#define CMDID_DOW_KSIEG_NORM						1248
#define CMDID_DOW_KSIEG_BO							1249
#define CMDID_DOW_KSIEG_BZ							1250
#define CMDID_DOW_KSIEG_BZ_OST						1251
#define CMDID_DZIENNIK_BO							1252
#define CMDID_DZIENNIK_BZ							1253
#define CMDID_DZIENNIK_BZ_OST						1254
#define CMDID_ZAKUP_IMPORT							1255
#define CMDID_OPTPAD_BO_BZ							1256
#define CMDID_WIZARD_BO_Z_BZ						1257
#define CMDID_RAPORT_SRTRW_TAB_AMOR					1258
#define CMDID_LISTA_PRACOWNIKOW						1259


#define CMDID_RAPORT_SRTRW_OPERACJE					1260
#define CMDID_GRUPASCHEMAT_NALICZEN					1261
#define CMDID_OPERKASA								1262
#define CMDID_OPERBANK								1263
#define CMDID_KOMPENSATA							1264
#define CMDID_INNE_SKLADNIKI						1265
#define CMDID_TERMIN_NALICZEN						1266
#define CMDID_WIZZARD_MULTICASH_IMPORT				1267
#define CMDID_OPTPAD_PLACE							1268

#define CMDID_RAP_PROLOJ							1269

#define CMDID_OPER_ZALICZKI							1270


#define CMDID_LISTA_ZD								1276
#define CMDID_LISTA_ZZ								1277
#define CMDID_LISTA_PW								1278
#define CMDID_LISTA_RW								1279
#define CMDID_LISTA_ZAPAK							1280
#define CMDID_LISTA_ROZPAK							1281
#define CMDID_LISTA_RP								1282
#define CMDID_LISTA_REALPROD						1283
#define CMDID_LISTA_PP								1284
#define CMDID_LISTA_MM								1285

#comment BEGIN BD_VER5 !!!!
#define CMDID_RAPORT_ZAKUP_VS_DOKMAG				1289
#comment END BD_VER5


#define CMDID_RAPORT_ZLECPROD_WG_KLIENT				1290
#define CMDID_RAPORT_ZLECPROD_WG_WYROBOW			1291
#define CMDID_RAPORT_ZLECPROD_SUROWCE_SUMA			1292
#define CMDID_RAPORT_ZLECPROD_SUROWCE_WG_KLIENTOW	1293
#define CMDID_RAPORT_ZLECPROD_SUROWCE_BRAK			1294
#define CMDID_OPTIONPAD_RAPORT_PRODUKCJA			1295
#define CMDID_RAPORT_TOWARY_BRAK					1296
#define CMDID_LISTA_ZAMOWIEN_WLASNYCH				1297
#define CMDID_LISTA_DOWOD_KSIEG						1298


#comment BEGIN BD_VER6 !!!!
#define CMDID_OPTIONPAD_ZAM_OF						1299
#define CMDID_OPTIONPAD_RAPORT_ROZLICZENIE_ETYKIET	1300						
#define CMDID_OPTIONPAD_RAPORT_ODCHYLENIE_RECEPT	1301
#comment END BD_VER6


#comment BEGIN BD_VER4 !!!!
#define CMDID_RAPORT_POTWIERDZENIE_SALD				1302
#comment END BD_VER4

#define CMDID_RAP_SP_ZYSK_DOK						1303
#define CMDID_RAP_SP_ZYSK_DOK_SZCZEGOLY				1304
#define CMDID_RAP_SP_ZYSK_PROD						1305


#comment BEGIN BD_VER4 !!!!
#define CMDID_RAPORT_MAG_DOKUMENTY_ROZCHODY				1306
#define CMDID_RAPORT_TOWARY_PRZYCH_BY_ART				1308
#define CMDID_RAPORT_TOWARY_ROZCH_BY_ART				1309
#define CMDID_RAPORT_SPRZEDAZ_ZESTAWIENIE_SZCZEGOLOWE	1310
#define CMDID_RAPORT_ZAKUP_ZESTAWIENIE_SZCZEGOLOWE		1311
#comment END BD_VER4



#define CMDID_OPTIONPAD_SPRZEDAZ					1312
#define CMDID_OPTIONPAD_ZAKUP						1313

#define CMDID_EXPLORER_SRTRW						1314
#define CMDID_RAPORT_VAT_STAWKAMI_ZAKUP				1315
#define CMDID_RAPORT_VAT_PODSUMOWANIE_ZAKUP			1316
#define CMDID_RAPORT_KLIENCI_RANKING				1317
#define CMDID_RAPORT_OPER_FINANS_SZCZEGOLY			1318
#define CMDID_RAPORT_STRUKT_WIEKOWA_ZO				1319

#define CMDID_WIZZARD_MULTICASH_EKSPORT				1320


#define CMDID_REZERWACJA							1321
#define CMDID_ZAKREZERWACJA							1322
#define CMDID_WIZZARD_NALICZENIE					1323

#define CMDID_BCS_EX_SLOW							1324
#define CMDID_BCS_EX_STAN							1325
#define CMDID_BCS_COMPARE_STANMAG					1326

#define CMDID_ROZLICZENIE_INTRASTAT					1327



#comment BEGIN BD_VER4 !!!!

#define CMDID_RAPORT_SPRZEDAZ_PODSUMOWANIE_WG_KLIENTOW	1328
#define CMDID_RAPORT_SPRZEDAZ_PODSUMOWANIE_WG_PRODUKTOW	1329
#define CMDID_RAPORT_SPRZEDAZ_PODSUMOWANIE_MIESIACAMI	1330

#define CMDID_RAPORT_SPRZEDAZ_SZCZEGOLY_WG_KLIENTOW_DOK		1331
#define CMDID_RAPORT_SPRZEDAZ_SZCZEGOLY_WG_KLIENTOW_PROD	1332
#define CMDID_RAPORT_SPRZEDAZ_PODSUMOWANIE_WG_PRODUKTOW_KLI	1333




#define CMDID_RAPORT_ZAKUP_PODSUMOWANIE_WG_KLIENTOW			1334
#define CMDID_RAPORT_ZAKUP_PODSUMOWANIE_WG_PRODUKTOW		1335
#define CMDID_RAPORT_ZAKUP_PODSUMOWANIE_MIESIACAMI			1336

#define CMDID_RAPORT_ZAKUP_SZCZEGOLY_WG_KLIENTOW_DOK		1337
#define CMDID_RAPORT_ZAKUP_SZCZEGOLY_WG_KLIENTOW_PROD		1338
#define CMDID_RAPORT_ZAKUP_PODSUMOWANIE_WG_PRODUKTOW_KLI	1339



#define CMDID_RAPORT_ZAMOBCE_PODSUMOWANIE_WG_DOKUMENTOW		1340
#define CMDID_RAPORT_ZAMOBCE_PODSUMOWANIE_WG_KLIENTOW		1341
#define CMDID_RAPORT_ZAMOBCE_PODSUMOWANIE_WG_PRODUKTOW		1342
#define CMDID_RAPORT_ZAMOBCE_PODSUMOWANIE_MIESIACAMI		1343


#define CMDID_RAPORT_ZAMWLASNE_PODSUMOWANIE_WG_DOKUMENTOW	1344
#define CMDID_RAPORT_ZAMWLASNE_PODSUMOWANIE_WG_KLIENTOW		1345
#define CMDID_RAPORT_ZAMWLASNE_PODSUMOWANIE_WG_PRODUKTOW	1346
#define CMDID_RAPORT_ZAMWLASNE_PODSUMOWANIE_MIESIACAMI		1347
#define CMDID_RAPORT_ZAMWLASNE_DO_REALIZACJI_WG_DOSTAWCOW	1348
#define CMDID_RAPORT_ZAMWLASNE_DO_REALIZACJI_WG_PRODUKTOW	1349



#define CMDID_RAPORT_REZERWACJE_DO_ZWOLNIENIA				1350

#define CMDID_MENU_KSIEGOWANIE_GRUPOWE						1351
#define CMDID_RAPORT_MAG_DOKUMENTY_PRZYCHODY				1352


#comment END BD_VER4



#comment BEGIN BD_VER6
#define CMDID_DB_BACKUP										1353
#define CMDID_RAPORT_PLACE_LISTA_WYNAGRODZEN				1354
#define CMDID_RAPORT_STRUKT_WIEKOWA_NAL_ODR					1355
#comment END BD_VER6


#comment BEGIN BD_VER7
#define CMDID_RAPORT_PLACE_CHOROBY_BY_PRACOWNIK				1356
#define CMDID_RAPORT_PLACE_CHOROBY_PODSUMOWANIE				1357
#define CMDID_RAPORT_PLACE_NIEOB_BY_PRACOWNIK				1358
#define CMDID_RAPORT_PLACE_NIEOB_PODSUMOWANIE_BY_PRAC		1359
#define CMDID_RAPORT_PLACE_NIEOB_PODSUMOWANIE_BY_TYP		1360
#comment END BD_VER7
#comment BEGIN_DB_ver8
#define CMDID_RAPORT_RCP_WG_PRACOWNIKOW						1361
#define CMDID_RAPORT_RCP_WG_KLIENTOW						1362
#comment END_DB_ver8

#comment -- nowe CMDID_ bez uprawnieñ - jak zrobisz uprawnienie przenieœ powy¿ej tej linii

#define CMDID_AKTUALIZACJA_CEN						1363
#define CMDID_WIZZARD_NAVISION_EKSPORT				1364
#define CMDID_WIZZARD_EDI_EKSPORT				    1365
#define CMDID_WIZZARD_SAP_EKSPORT				    1375
#define CMDID_WIZZARD_EKSP_PLIKOW_Z_BAZY			1367
#define CMDID_GENERATOR_CEN							1368

#define CMDID_FAKTURA_VAT						3000
#define CMDID_FAKTURA_VAT_KOREKTA				3001
#define CMDID_RACHUNEK							3002
#define CMDID_RACHUNEK_KOREKTA					3003
#define CMDID_SPRZEDAZ_DETALICZNA				3004
#define CMDID_ZAKUP								3005
#define CMDID_ZAMOWIENIE_OBCE					3006
#define CMDID_PZ								3007
#define CMDID_WZ								3008
#define CMDID_PW								3009
#define CMDID_RW								3010
#define CMDID_ZD								3011
#define CMDID_ZZ								3012
#define CMDID_MR								3013
#define CMDID_MP								3014
#define CMDID_MM								3015
#define CMDID_PP								3016
#define CMDID_RP								3017
#define CMDID_IP								3018
#define CMDID_IR								3019


#define CMDID_FAKTURA_VAT_KOREKTA_VIEW				3020
#define CMDID_RACHUNEK_KOREKTA_VIEW					3021
#define CMDID_PARAGON_KOREKTA_VIEW					3022
#define CMDID_FAKTURA_EXP_KOREKTA_VIEW				3023
#define	CMDID_ZAKUP_KOREKTA							3024
#define CMDID_ZAKUP_KOREKTA_VIEW					3025
#define CMDID_LISTA_PLAC							3026
#define CMDID_GRUPA_ZASZEREGOWANIA					3027
#define CMDID_N5PLWZORLP							3028
#define CMDID_FAKTURA_VAT_WNT						3029
#define CMDID_FAKTURA_VAT_WNT_KOREKTA				3030
#define CMDID_FAKTURA_VAT_WNT_KOREKTA_VIEW			3031
#define CMDID_FAKTURA_VAT_WDT						3032
#define CMDID_FAKTURA_VAT_WDT_KOREKTA				3033
#define CMDID_FAKTURA_VAT_WDT_KOREKTA_VIEW			3034

#define CMDID_N5PLKALCP								3035

#define CMDID_FAKTURA_ZAKUPU_RR						3036
#define CMDID_KOREKTA_FAKTURY_ZAKUPU_RR				3037

#define CMDID_PARAGON								3038
#define CMDID_PARAGON_KOREKTA						3039
#define CMDID_FAKTURA_EXP							3040
#define CMDID_FAKTURA_EXP_KOREKTA					3041

#define CMDID_FAKTURA_IMPORTOWA_KOREKTA				3042
#define CMDID_FAKTURA_IMPORTOWA_KOREKTA_VIEW		3043


#define CMDID_ROZLICZENIE_PIT11						3044
#define CMDID_ROZLICZENIE_PIT5						3045
#define CMDID_ROZLICZENIE_PIT5L						3046


#define CMDID_OPTIONPAD_RAPORT_SPRZEDAZ				3047
#define CMDID_OPTIONPAD_RAPORT_ZAKUP				3048
#define CMDID_OPTIONPAD_RAPORT_ZAMOBCE				3049
#define CMDID_OPTIONPAD_RAPORT_ZAMWLASNE			3050

#define CMDID_RAPKAS								3051
#define CMDID_FAKTURA_ZALICZKA						3052
#define CMDID_RAPBANK								3053


#define CMDID_ZAPYTANIE_OF_OBCE					3054
#define CMDID_ZAPYTANIE_OF_WLASNE				3055
#define CMDID_OFERTY_OBCE						3056
#define CMDID_OFERTY_WLASNE						3057
#define CMDID_ROZLICZENIE_PIT4					3058
#define CMDID_KWZ								3059


#comment DB6
#define CMDID_EWIDENCJA_ETYKIET_TWORZENIE		3085
#define CMDID_EWIDENCJA_ETYKIET_KONTROLA		3086
#define CMDID_EWIDENCJA_ETYKIET_ZDANIE			3087
#define CMDID_EWIDENCJA_ETYKIET_KASACJA			3088


#comment BEGIN DB_VER8
#define CMDID_KLIENT_OBIEKT						3089
#define CMDID_PLRCP								3090
#define CMDID_PLTYPPRACY						3091
#define CMDID_ROLA								3092
#define CMDID_ROLAPRIOR							3093
#define CMDID_SPRZEDAZ_DETALICZNA_KOREKTA		3094

#comment END DB_VER8

#define CMDID_OPTIONPAD_GANDG_TRANSFER			3095
#define CMDID_GANDG_SUMMARY_INFO				3096
#define CMDID_PROTOKOL_SERWISOWY				3097

#comment DB14_A
#define CMDID_IMPORT_USLUG						3098
#define CMDID_KOR_IMPORT_USLUG					3099

#define CMDID_RAPORT_MARSER						1365
#define CMDID_RAPORT_RAND_MASZYNY				1366

#define CMDID_SPRZEDAZ_DET_PARAG				1370
#define CMDID_SPRZEDAZ_DET_FVAT					1371
#define CMDID_LISTA_DOK_OTWARTE					1372
#define CMDID_LISTA_DOK_OTWARTE_KASA			1373
#define CMDID_WIZZARD_BRAKUJACE_WZ				1374
#define CMDID_REJESTRACJA_USLUG					1375
#define CMDID_WIZZARD_NIEZAFAKT_OPAK			1376
#define CMDID_KREATOR_KOREKT                    1377
#define CMDID_SEARCH_CUSTOMER_OBJECT			1378
#define CMDID_IMPORT_ZAMOWIEN					1379
#define CMDID_IMPORT_PROTUS						1380
#define CMDID_POJAZD							1381
#define CMDID_RAPORT_DLA_SZEFA					1382

#define CMDID_TORAL_MOD_2034_SPRZ_WEGLA			1383
#define CMDID_TORAL_MOD_2027_OPMAG_EGZ			1384
#define CMDID_MASZYNA_TORAL						1385
#define CMDID_ANKIETA_TORAL						1386
#define CMDID_RAPORT_MARSER_2					1387
#define CMDID_WIZZARD_FVAT_TO_PDF				1388
#define CMDID_WIZZARD_WZ_TO_FVAT				1389
#define CMDID_STRAZNIK_CEN						1390
#define CMDID_RAPORT_DEKRETOW					1391
#define CMDID_RAPORT_PRODUKTY_RP_ZALEGAJACE		1392
#define CMDID_RAPORT_ZLECPROD_NIEZREALIZOWANE   1393
#define CMDID_TRANSAKCJE_NIEPOWIAZANE			1394
#define CMDID_KREATOR_FAKTUR_DO_WYSYLKI			1395
#define CMDID_RAPORT_WIEKOWANIE_TOWAROW         1396
#define CMDID_RAPORT_IMPORT_WYCIAGOW_BANKOWYCH  1397
#define CMDID_KREATOR_DOKUMENTOW_DO_WYSYLKI		1398
#define CMDID_RAPORT_RENT_WG_PRACOWNIK_DEDYK	1399
#define CMDID_ZESTAW							1400
#define CMDID_RAPORT_ZAPOTRZEB_NA_PRODUKTY		1401