
#define TYPEID_GLOBPROFILE				10010
#define TYPEID_USERPROFILE				10011
#define TYPEID_LICENCE_INFORMATION		8002
#define TYPEID_N5WIZZARDEMAILDOKUMELEM	10126
#define TYPEID_N5WIZZARDEMAIL			10127
#define TYPEID_N5SENDEMAIL				10128



#define APP_NAME					"EB"

#define EB_MOD_MASK_HANDEL		1
#define EB_MOD_MASK_MAGAZYN		2
#define EB_MOD_MASK_KONTAKT		4
#define EB_MOD_MASK_PRODUKCJA	8
#define EB_MOD_MASK_FINANSE		16
#define EB_MOD_MASK_PRACOWNIK	32


#define MAX_LIC_YEARS				5
#define TMP_DAYS					30

