
#ifndef _H1232_H_
#define _H1232_H_

#macro UOR_READ(_typeid_)	_typeid_##STDR_READ
#macro UOR_UPDATE(_typeid_)	_typeid_##STDR_UPDATE
#macro UOR_DELETE(_typeid_)	_typeid_##STDR_DELETE
#macro UOR_INSERT(_typeid_)	_typeid_##STDR_INSERT

#macro UAR_CMDID(_cmdid_)	_cmdid_##STDR_READ


#define UAR_POWIAZANIA			8000##STDR_READ
#define UAR_PLUGIN_FAKTURY		8001##STDR_READ




#define UAR_RACHUNEK		CMDID_RACHUNEK##1000
#define UAR_PARAGON			CMDID_PARAGON##1000
#define UAR_FVAT			CMDID_FAKTURA_VAT##1000
#define UAR_KFVAT			CMDID_FAKTURA_VAT_KOREKTA##1000
#define UAR_KORRACHUNEK		CMDID_RACHUNEK_KOREKTA##1000
#define UAR_KORPARAGON		CMDID_PARAGON_KOREKTA##1000
#define UAR_FWDT			CMDID_FAKTURA_VAT_WDT##1000
#define UAR_FEXP			CMDID_FAKTURA_EXP##1000
#define UAR_KFEXP			CMDID_FAKTURA_EXP_KOREKTA##1000
#define UAR_FKWDT			CMDID_FAKTURA_VAT_WDT_KOREKTA##1000
#define UAR_ZALICZKA		CMDID_FAKTURA_ZALICZKA##1000


#define UAR_DOKMAG_PZ		CMDID_PZ##1000
#define UAR_DOKMAG_WZ		CMDID_WZ##1000
#define UAR_DOKMAG_ZD		CMDID_ZD##1000
#define UAR_DOKMAG_KWZ		CMDID_KWZ##1000
#define UAR_DOKMAG_ZZ		CMDID_ZZ##1000
#define UAR_DOKMAG_PW		CMDID_PW##1000
#define UAR_DOKMAG_RW		CMDID_RW##1000
#define UAR_DOKMAG_PP		CMDID_PP##1000
#define UAR_DOKMAG_RP		CMDID_RP##1000
#define UAR_DOKMAG_IP		CMDID_IP##1000
#define UAR_DOKMAG_IR		CMDID_IR##1000
#define UAR_DOKMAG_MM		CMDID_MM##1000
#define UAR_DOKMAG_MP		CMDID_MP##1000
#define UAR_DOKMAG_MR		CMDID_MR##1000
#define UAR_DOKMAG_REZERW	CMDID_REZERWACJA##1000
#define UAR_DOKMAG_ZREZERW	CMDID_ZAKREZERWACJA##1000



#define UAR_ZAMO		CMDID_ZAMOWIENIE_OBCE##1000
#define UAR_ZAMW		CMDID_ZAMOWIENIE_WLASNE##1000
#define UAR_ZAP_OF_O	CMDID_ZAPYTANIE_OF_OBCE##1000
#define UAR_ZAP_OF_W	CMDID_ZAPYTANIE_OF_WLASNE##1000
#define UAR_OF_O		CMDID_OFERTY_OBCE##1000
#define UAR_OF_W		CMDID_OFERTY_WLASNE##1000						



#define UAR_ZAKUP						CMDID_ZAKUP##1000
#define UAR_ZAKUP_KOREKTA				CMDID_ZAKUP_KOREKTA##1000
#define UAR_ZAKUP_RR					CMDID_FAKTURA_ZAKUPU_RR##1000	
#define UAR_ZAKUP_RR_KOREKTA			CMDID_KOREKTA_FAKTURY_ZAKUPU_RR##1000
#define UAR_ZAKUP_WNT					CMDID_FAKTURA_VAT_WNT##1000
#define UAR_ZAKUP_WNT_KOREKTA			CMDID_FAKTURA_VAT_WNT_KOREKTA##1000
#define UAR_ZAKUP_IMPORT				CMDID_ZAKUP_IMPORT##1000
#define UAR_ZAKUP_IMPORT_KOREKTA		CMDID_FAKTURA_IMPORTOWA_KOREKTA##1000
#define UAR_ZAKUP_IMPORT_USLUG			CMDID_IMPORT_USLUG##1000
#define UAR_ZAKUP_KOR_IMPORT_USLUG		CMDID_KOR_IMPORT_USLUG##1000

#define UAR_CUSTOMER_FIRM				CMDID_KLIENT_FIRMA##1000
#define UAR_CUSTOMER_PRIV				CMDID_KLIENT_OSOBA_PRYWATNA##1000
#define UAR_JEDNOSTKA					CMDID_MIARA##1000
#define UAR_WALUTA						CMDID_WALUTA##1000	

#define UAR_ZAPAK						CMDID_PAKOWANIE##1000	
#define UAR_ROZPAK						CMDID_ROZPAKOWANIE##1000	



#comment UAR_CUSTO_RIGHTS_FROM								120000
#comment TODO - do preloadu!!!

#comment W db4 - 50312
#define UAR_PRZEKROCZ_LIMIT			120001

#comment W operacjach specjalnych - 50310
#define UAR_MANAGE_RIGHTS			120002

#comment W db4 - 50312
#define UAR_SPRZED_PONIZEJ_MIN		120003

#comment W db4 - 50312
#define UAR_SPRZEDAZ_ZMIEN_SPOS_VAT		120004


#comment W db5 - 50314
#define UAR_ZAMKNIJ_OKRES					120005
#define UAR_BLOKUJ_OKRES_KSIEG				120006
#define UAR_PARAGON_EDYTUJ_PO_FISK			120007
#define UAR_USTALANIE_LIMITU_KREDYTOWEGO	120008




#comment W db6 - 50315
#define UAR_BLOKADA_SPRZEDAZY_SET					120009
#define UAR_BLOKADA_SPRZEDAZY_REMOVE				120010
#define UAR_DRUKUJ_PONOWNIE_ETYKIETY				120011
#define UAR_BLOKADA_ZMIANY_DATY_WYSTAWIENIA			120015

#comment w db9 - security (50323)
#define UAR_KLOB_SEC_ATRYBUTY_READ					120012
#define UAR_KLOB_SEC_ATRYBUTY_EDIT					120013

#define UAR_BLOKADA_MODULU_EURO_HANDEL				120016
#define UAR_BLOKADA_MODULU_EURO_MAGAZYN				120017
#define UAR_BLOKADA_MODULU_EURO_KONTAKT				120018
#define UAR_BLOKADA_MODULU_EURO_PRODUKCJA			120019
#define UAR_BLOKADA_MODULU_EURO_FINANSE				120020
#define UAR_BLOKADA_MODULU_EURO_PRACOWNIK			120021

#define UAR_DOSTEP_CENA_KARTOTEKOWA_1               120022
#define UAR_DOSTEP_CENA_KARTOTEKOWA_2               120023
#define UAR_DOSTEP_CENA_KARTOTEKOWA_3               120024 
#define UAR_DOSTEP_CENA_KARTOTEKOWA_4               120025
#define UAR_DOSTEP_CENA_KARTOTEKOWA_5               120026
#define UAR_DOSTEP_CENA_KARTOTEKOWA_6               120027

#define UAR_BLOKADA_EDYCJI_HASLA_ABAS_INWESTYCJE	120028
#define UAR_BLOKADA_EDYCJI_POZYCJI_DOK_MAG			120029

#comment  120030..120034 uzywane ale nie wpisane

#define UAR_POKAZUJ_CENY_ZAKUPU						120035
#define UAR_DOSTEP_UZYTKOWNIKA_DO_DANYCH_KLIENTOW   120036

#comment 120037..120040 dostêp do oddzia³ów (Rand)
#define UAR_DOSTEP_ODDZIAL_WROCLAW				    120037
#define UAR_DOSTEP_ODDZIAL_POZNAN				    120038
#define UAR_DOSTEP_ODDZIAL_KATOWICE				    120039
#define UAR_DOSTEP_ODDZIAL_KRAKOW				    120040

#comment uprawnienie do uzupe³niania uwag dla produktów sprzeda¿y ogólnej (Grajewscy)
#define UAR_ADD_UWAGI_SPRZEDAZ_OGOLNA			    120041

#comment tryby dowolnych uprawnieñ u¿ytkownika
#define UAR_OGRANICZONY_DOSTEP_DANE_KLIENTA         1
#define UAR_DOSTAWCA_OGRANICZONY_DOSTEP				2

#define UAR_ZMIANA_RACHUNKOW_BANKOWYCH_DOSTAWCY 120042

#comment blokada mo¿liwoœci wyboru pracownika na dokumencie kasowym / bankowym (PrintyLand)
#define UAR_BLOKADA_PRACOWNIKA_PLATNOSC			120043

#comment W operacjach specjalnych - 50310
#define UAR_MANAGE_KLIENT_GRUPA_PROD			1200044

#comment Blokada wystawiania OW i ZO w cenach ni¿szych ni¿ cena ostatniej dostawy (Abakosteel)
#define UAR_BLOKADA_WYSTAWIANIA_ZO_PONIZEJ_CENY_DOSTAWY		120044

#endif
