#define INTID_TYPDOKUMENTU_DOKUMENTY					1
#define INTID_TYPDOKUMENTU_ODEBRANYEMAIL				2
#define INTID_TYPDOKUMENTU_ODEBRANYZALACZNIKEMAIL		3
#define INTID_REJESTRDOK_REJESTRBANKOWY					1
#define INTID_REJESTRDOK_REJESTRFAKTUR					2
#define INTID_REJESTRDOK_REJESTRKASOWY					3
#define INTID_REJESTRDOK_REJESTRKOREKTFAKTUR			4
#define INTID_REJESTRDOK_REJESTRKOREKTRACHUNKOW			5	
#define INTID_REJESTRDOK_REJESTRPARAGONOWIWZ			6
#define INTID_REJESTRDOK_REJESTRRACHUNKOW				7
#define INTID_TYPDZIALANIA_ODBIOR_LISTU					010101
#define INTID_TYPDZIALANIA_ODBIOR_EMAILA				010102
#define INTID_TYPDZIALANIA_ODBIOR_FAXU					010103
#define INTID_TYPDZIALANIA_ODEBRANY_TELEFON				010201
#define INTID_TYPDZIALANIA_WYKONANY_TELEFON				010202


